const COP=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0);
const KEY='lhAdminV4', OLD='lhAdminV3', GAME=2000; let catalog=[];
let S=JSON.parse(localStorage.getItem(KEY)||'null')||migrate(JSON.parse(localStorage.getItem(OLD)||'null'))||init();
function init(){return{version:4,tables:[...Array(4)].map((_,i)=>({id:'B'+(i+1),type:'billar',name:'Billar '+(i+1),account:null})).concat([...Array(18)].map((_,i)=>({id:'C'+(i+1),type:'consumo',name:'Consumo '+(i+1),account:null}))),sales:[],expenses:[],shifts:[],inventory:{},waitresses:['Mesera turno 1','Mesera turno 2'],audit:[]}}
function migrate(o){if(!o)return null;o.version=4;o.audit=o.audit||[];for(const x of o.tables||[]){if(x.account&&x.type==='billar'){let a=x.account;a.rounds=a.rounds||[];for(const g of a.games||[])a.rounds.push({id:Date.now()+Math.random(),status:'closed',loser:g.loser||'Sin identificar',items:g.items||[],gameFee:GAME,createdAt:new Date().toISOString(),closedAt:new Date().toISOString()});a.games=[];a.activeRound=a.activeRound||{id:Date.now()+Math.random(),status:'active',items:[],createdAt:new Date().toISOString(),source:'Nueva partida'};a.players=a.players||[];a.playerExtras=a.playerExtras||[];a.payments=a.payments||[]}}return o}
function save(note){if(note)S.audit.push({ts:new Date().toISOString(),note});localStorage.setItem(KEY,JSON.stringify(S));renderHome()}
function stamp(){return new Date().toLocaleString('es-CO')};function t(id){return S.tables.find(x=>x.id===id)}
fetch('catalog.json').then(r=>r.json()).then(x=>{catalog=x;for(const p of catalog)if(S.inventory[p.id]==null)S.inventory[p.id]=p.stock;save();renderInventory()});
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='inventory')renderInventory();if(id==='sales')renderSales();if(id==='reports')renderReports();if(id==='expenses')renderExpenses();if(id==='shifts')renderShift()}
function modal(h){sheet.innerHTML=h;modalEl.classList.add('show')}function closeModal(){modalEl.classList.remove('show')}function backToTables(type){closeModal();showTables(type)}function modalNav(back,label='Volver'){return `<div class="modalNav"><button class="navBack" onclick="${back}">← ${label}</button><button class="navHome" onclick="closeModal();showView('home')">🏠 Inicio</button></div>`}
function roundConsumption(r){return(r?.items||[]).reduce((s,i)=>s+i.price*i.qty,0)}
function grossTotal(a){return(a?.rounds||[]).reduce((s,r)=>s+GAME+roundConsumption(r),0)+(a?.loose||[]).reduce((s,i)=>s+i.price*i.qty,0)+(a?.playerExtras||[]).reduce((s,i)=>s+i.price*i.qty,0)}
function paidTotal(a){return(a?.payments||[]).reduce((s,p)=>s+p.amount,0)}
function closedTotal(a){return Math.max(0,grossTotal(a)-paidTotal(a))}
function pendingTotal(a){return roundConsumption(a?.activeRound)}
function displayTotal(a,type){return closedTotal(a)+(type==='billar'?pendingTotal(a):0)}
function renderHome(){let today=new Date().toDateString(),p=S.sales.filter(x=>new Date(x.ts).toDateString()===today);kSales.textContent=COP(p.reduce((s,x)=>s+x.total,0));kCash.textContent=COP(p.reduce((s,x)=>s+x.cash,0));kTransfer.textContent=COP(p.reduce((s,x)=>s+x.transfer,0));kOpen.textContent=S.tables.filter(x=>x.account).length;status.innerHTML=`<p>🎱 ${S.tables.filter(x=>x.type==='billar'&&x.account).length}/4 mesas de billar activas</p><p>🍺 ${S.tables.filter(x=>x.type==='consumo'&&x.account).length}/18 mesas de consumo activas</p><p>📦 ${catalog.filter(p=>(S.inventory[p.id]||0)<=5&&p.type==='stock').length} productos con existencia ≤ 5</p>`}
function showTables(type){showView('tablesView');tablesTitle.textContent=type==='billar'?'🎱 Mesas de billar':'🍺 Mesas de consumo';tables.innerHTML=S.tables.filter(x=>x.type===type).map(x=>`<div class="card tableCard ${x.account?'busy':''}"><span class="pill">${x.account?(type==='billar'?'EN JUEGO':'ABIERTA'):'DISPONIBLE'}</span><h3>${x.name}</h3><div>${x.account?x.account.group:'Libre'}</div><div class="amt">${x.account?COP(displayTotal(x.account,x.type)):'—'}</div>${x.account?`<div class="actions"><button class="primary" onclick="openAccount('${x.id}')">Gestionar</button>${x.type==='billar'?`<button onclick="openCustomer('${x.id}')">📺 Cliente</button>`:''}<button onclick="move('${x.id}')">⇄</button><button class="gold" onclick="pay('${x.id}')">Cobrar</button></div>`:`<button onclick="newAccount('${x.id}')">+ Abrir cuenta</button>`}</div>`).join('')}
function newAccount(id){let x=t(id);modal(`${modalNav("backToTables('${x.type}')",'Mesas')}<h2>Abrir ${x.name}</h2><div class="field"><label>Cliente / grupo</label><input id="group" placeholder="Ej. Carlos y amigos"></div><div class="field"><label>Mesera</label><select id="waitress">${S.waitresses.map(x=>`<option>${x}</option>`).join('')}</select></div><button class="gold wide" onclick="confirmOpen('${id}')">Abrir cuenta</button>`)}
function confirmOpen(id){let x=t(id);x.account={group:group.value||'Cliente',waitress:waitress.value,rounds:[],activeRound:x.type==='billar'?newRound('Nueva partida'):null,loose:[],history:[stamp()+' · Cuenta abierta'],players:[],people:[],playerExtras:[],payments:[]};save(`Cuenta abierta ${x.name}`);closeModal();openAccount(id)}
function newRound(source='Nueva partida',items=[]){return{id:Date.now()+Math.random(),status:'active',items:items.map(i=>({...i})),createdAt:new Date().toISOString(),source}}
function openAccount(id){let x=t(id),a=x.account;if(x.type==='billar')openBilliard(id);else openConsumption(id)}
function openBilliard(id){let x=t(id),a=x.account,r=a.activeRound||newRound();a.activeRound=r;let n=(a.rounds?.length||0)+1;modal(`${modalNav("backToTables('billar')",'Mesas')}<div class="accountHead"><div><small>${x.name} · ${a.group}</small><h2>🎱 Partida ${n}</h2><span class="state activeState">● EN CURSO</span></div><div class="roundMoney"><small>Consumo ronda</small><strong>${COP(roundConsumption(r))}</strong></div></div><div class="notice compact">Los productos se acumulan en esta ronda. Al terminar, consumo + ${COP(GAME)} se asignan al perdedor.</div><div class="quickActions"><button class="finish" onclick="finishRound('${id}')">🏁 Terminar partida</button><button onclick="duplicatePreview('${id}')" ${a.rounds.length?'':'disabled'}>🔁 Duplicar anterior</button><button onclick="extraPlayer('${id}')">➕ Extra persona</button><button onclick="openCustomer('${id}')">📺 Vista cliente</button></div><section class="orderPanel"><div class="orderTitle"><div><small>COMANDA ACTIVA</small><h3>🧾 Pedido · Partida ${n}</h3></div><div><small>Subtotal</small><strong>${COP(roundConsumption(r))}</strong></div></div><div class="orderCart">${roundItems(r,id)}</div></section><div class="chips">${categoryButtons(id)}</div><input class="search" id="prodSearch" placeholder="🔎 Buscar producto…" oninput="renderProducts('${id}')"><div id="productBox" class="products"></div><h3>Cuentas acumuladas</h3><div class="card inner">${playerBalances(a,id)}</div><h3>Historial de partidas</h3><div class="card inner">${roundHistory(a,id)}</div><div class="stickyActions"><button onclick="move('${id}')">⇄ Cambiar mesa</button><button onclick="viewAccount('${id}')">🧾 Ver cuenta</button><button class="gold" onclick="pay('${id}')">💰 Cobrar</button></div>`);renderProducts(id)}
function openConsumption(id){let x=t(id),a=x.account;modal(`${modalNav("backToTables('consumo')",'Mesas')}<h2>🍺 ${x.name} · ${a.group}</h2><p>Mesera: <b>${a.waitress}</b></p><div class="total">${COP(closedTotal(a))}</div><div class="chips">${categoryButtons(id)}</div><input class="search" id="prodSearch" placeholder="🔎 Buscar producto…" oninput="renderProducts('${id}')"><div id="productBox" class="products"></div><h3>Consumos</h3><div class="card inner">${looseItems(a)}</div><div class="stickyActions"><button onclick="move('${id}')">⇄ Cambiar mesa</button><button onclick="viewAccount('${id}')">🧾 Ver cuenta</button><button class="gold" onclick="pay('${id}')">💰 Cobrar</button></div>`);renderProducts(id)}
let activeCategory='Todos';function categoryButtons(id){let cats=['Todos','CERVEZAS','CUBETAZOS','MICHELADAS','GASEOSAS','LICORES','OTROS'];return cats.map(c=>`<button onclick="setCat('${id}','${c}')">${c==='Todos'?'⭐':c==='CERVEZAS'?'🍺':c==='CUBETAZOS'?'🪣':c==='MICHELADAS'?'🍹':c==='GASEOSAS'?'🥤':c==='LICORES'?'🥃':'🍬'} ${c}</button>`).join('')}
function setCat(id,c){activeCategory=c;renderProducts(id)}
function simpleName(n){return n.replace(/\s+[xX]\d+.*$/,'').replace(/\s+\d+\s*(cc|c|ml).*$/i,'').replace('Buweiser','Budweiser').trim()}
function catMatch(p,c){let z=p.category.toUpperCase(),n=p.name.toUpperCase();if(c==='Todos')return true;if(c==='CERVEZAS')return z.includes('CERVEZA');if(c==='CUBETAZOS')return z.includes('CUBET');if(c==='MICHELADAS')return z.includes('MICHEL')||n.includes('MICHEL');if(c==='GASEOSAS')return z.includes('GASEOSA')||z.includes('ENERG');if(c==='LICORES')return z.includes('AGUARD')||z.includes('LICOR')||z.includes('WHISK')||z.includes('RON');if(c==='OTROS')return !['CERVEZAS','CUBETAZOS','MICHELADAS','GASEOSAS','LICORES'].some(x=>catMatch(p,x));return true}
function renderProducts(id){let q=(prodSearch?.value||'').toLowerCase();let x=t(id),r=x?.account?.activeRound;let arr=catalog.filter(p=>p.price>0&&p.name.toLowerCase().includes(q)&&catMatch(p,activeCategory)).slice(0,36);productBox.innerHTML=arr.map(p=>{let qty=r?.items?.find(z=>z.id===p.id)?.qty||0;return `<div class="prod"><button onclick="addProduct('${id}','${p.id}')"><b>${simpleName(p.name)}</b>${qty?`<span class="prodQty">×${qty}</span>`:''}<br><span>${COP(p.price)}</span></button></div>`}).join('')||'<p>No hay productos en esta categoría.</p>'}
function consumeInventory(p,qty=1){if(p.recipe?.length){for(const r of p.recipe)S.inventory[r.productId]=(S.inventory[r.productId]||0)-r.qty*qty}else if(p.type==='stock')S.inventory[p.id]=(S.inventory[p.id]||0)-qty}
function addProduct(id,pid){let x=t(id),a=x.account,p=catalog.find(z=>z.id===pid);if(x.type==='billar'){let r=a.activeRound||(a.activeRound=newRound());let it=r.items.find(z=>z.id===pid);it?it.qty++:r.items.push({id:pid,name:simpleName(p.name),price:p.price,qty:1,addedAt:new Date().toISOString(),extra:r.source.startsWith('Duplicada')});}else{let it=a.loose.find(z=>z.id===pid);it?it.qty++:a.loose.push({id:pid,name:simpleName(p.name),price:p.price,qty:1,addedAt:new Date().toISOString()})}consumeInventory(p);a.history.push(stamp()+' · '+simpleName(p.name));save(`Producto ${simpleName(p.name)} en ${x.name}`);openAccount(id)}
function roundItems(r,id){return r.items.length?r.items.map(i=>`<div class="orderLine"><div><b>${i.name}</b><small>${COP(i.price)} c/u</small></div><div class="qtyCtl"><button class="mini" onclick="activeRoundQty('${id}','${i.id}',-1)">−</button><b>${i.qty}</b><button class="mini" onclick="activeRoundQty('${id}','${i.id}',1)">+</button><strong>${COP(i.price*i.qty)}</strong></div></div>`).join(''):'<div class="emptyOrder">Toca un producto del catálogo para agregarlo a esta ronda.</div>'}
function activeRoundQty(id,pid,delta){let x=t(id),a=x.account,r=a.activeRound;if(!r)return;let it=r.items.find(z=>z.id===pid),p=catalog.find(z=>z.id===pid);if(!it&&delta>0&&p){r.items.push({id:pid,name:simpleName(p.name),price:p.price,qty:1,addedAt:new Date().toISOString()});consumeInventory(p)}else if(it){if(delta>0){it.qty++;if(p)consumeInventory(p)}else{it.qty--;if(p)restoreInventory(p);if(it.qty<=0)r.items=r.items.filter(z=>z.id!==pid)}}a.history.push(stamp()+` · Ajuste ronda actual: ${p?simpleName(p.name):pid} ${delta>0?'+1':'-1'}`);save('Ajuste ronda actual');openBilliard(id)}
function looseItems(a){return a.loose.length?a.loose.map(i=>`<div class="item"><span>${i.name} × ${i.qty}</span><b>${COP(i.price*i.qty)}</b></div>`).join(''):'<small>Sin consumos.</small>'}
function finishRound(id){let x=t(id),a=x.account,r=a.activeRound;if(!r)return;let known=[...new Set([...(a.players||[]),...(a.people||[]).filter(x=>x.role==='player').map(x=>x.name),...(a.rounds||[]).map(z=>z.loser)])];modal(`${modalNav("openBilliard('${id}')",'Partida')}<h2>🏁 Terminar partida ${(a.rounds?.length||0)+1}</h2><p>Consumo: <b>${COP(roundConsumption(r))}</b><br>Chico: <b>${COP(GAME)}</b><br>Total a asignar: <b class="goldText">${COP(roundConsumption(r)+GAME)}</b></p><div class="field"><label>¿Quién perdió?</label><input id="loserName" list="players" placeholder="Nombre del perdedor"><datalist id="players">${known.map(n=>`<option value="${n}">`).join('')}</datalist></div><button class="finish wide" onclick="confirmFinish('${id}')">Confirmar y asignar cuenta</button><button class="wide" onclick="openBilliard('${id}')">Cancelar</button>`)}
function confirmFinish(id){let x=t(id),a=x.account,n=loserName.value.trim();if(!n)return alert('Debes identificar al perdedor.');let r=a.activeRound;r.status='closed';r.loser=n;r.gameFee=GAME;r.closedAt=new Date().toISOString();a.rounds.push(r);a.players=[...new Set([...(a.players||[]),n])];a.people=a.people||[];if(!a.people.some(x=>x.name===n))a.people.push({name:n,role:'player'});a.history.push(stamp()+` · Partida ${a.rounds.length} asignada a ${n}: ${COP(roundConsumption(r)+GAME)}`);a.activeRound=newRound('Nueva partida');save(`Partida ${a.rounds.length} de ${x.name} asignada a ${n}`);openBilliard(id)}
function duplicatePreview(id){let a=t(id).account,last=a.rounds[a.rounds.length-1];if(!last)return;modal(`${modalNav("openBilliard('${id}')",'Partida')}<h2>🔁 Duplicar partida anterior</h2><p>Se copiará únicamente el pedido. <b>No se copiará el perdedor.</b></p><div class="card inner">${last.items.map(i=>`<div class="item"><span>${i.name} × ${i.qty}</span><b>${COP(i.price*i.qty)}</b></div>`).join('')||'Sin productos'}</div><div class="total">Pedido: ${COP(roundConsumption(last))}</div><p class="notice compact">Al confirmar, estas unidades se descuentan del inventario como un nuevo despacho. Después podrás agregar extras.</p><button class="gold wide" onclick="confirmDuplicate('${id}')">Duplicar pedido</button><button class="wide" onclick="openBilliard('${id}')">Cancelar</button>`)}
function confirmDuplicate(id){let a=t(id).account,last=a.rounds[a.rounds.length-1];if(!last)return;let items=last.items.map(i=>({...i,addedAt:new Date().toISOString(),extra:false}));for(const i of items){let p=catalog.find(z=>z.id===i.id);if(p)consumeInventory(p,i.qty)}a.activeRound=newRound(`Duplicada de partida ${a.rounds.length}`,items);a.history.push(stamp()+` · Pedido de partida ${a.rounds.length} duplicado`);save(`Partida duplicada en ${t(id).name}`);openBilliard(id)}
function playerMap(a){let m={};for(const r of a.rounds||[])m[r.loser]=(m[r.loser]||0)+GAME+roundConsumption(r);for(const e of a.playerExtras||[])m[e.player]=(m[e.player]||0)+e.price*e.qty;for(const p of a.payments||[])m[p.player]=(m[p.player]||0)-p.amount;return m}
function playerBalances(a,id){let m=playerMap(a);return Object.keys(m).length?Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="item"><button class="playerLink" onclick="playerAccount('${id||''}','${esc(n)}')">👤 <b>${n}</b></button><b>${COP(v)}</b></div>`).join(''):'<small>Aún no hay cuentas asignadas.</small>'}
function esc(s){return String(s).replace(/'/g,"\\'")}
function roundHistory(a,id){return(a.rounds||[]).length?[...a.rounds].reverse().map(r=>`<div class="item"><span>Partida ${a.rounds.indexOf(r)+1} · <b>${r.loser}</b><br><small>${r.items.map(x=>`${x.name} ×${x.qty}`).join(' · ')||'Sin consumo'}</small></span><span><b>${COP(GAME+roundConsumption(r))}</b>${id?`<br><button class="mini" onclick="editRound('${id}',${a.rounds.indexOf(r)})">✏️ Editar</button>`:''}</span></div>`).join(''):'<small>Sin partidas finalizadas.</small>'}
function viewAccount(id){let x=t(id),a=x.account;modal(`${modalNav("openAccount('"+id+"')",'Orden')}<h2>🧾 Cuenta · ${x.name}</h2><p>${a.group} · Mesera: ${a.waitress}</p>${x.type==='billar'?`<h3>Por jugador</h3>${playerBalances(a,id)}<button class="wide" onclick="extraPlayer('${id}')">➕ Agregar extra a jugador</button><h3>Partidas</h3>${roundHistory(a,id)}${pendingTotal(a)?`<div class="notice">Hay una ronda en curso con ${COP(pendingTotal(a))} de consumo aún sin perdedor.</div>`:''}`:`${looseItems(a)}`}<div class="total">Saldo pendiente: ${COP(closedTotal(a))}</div><button class="gold wide" onclick="pay('${id}')">💰 Cobrar por jugador</button><button class="wide" onclick="openAccount('${id}')">Volver</button>`)}
function peopleList(a){let out=[];for(const n of a.players||[])if(n&&!out.some(x=>x.name===n))out.push({name:n,role:'player'});for(const x of a.people||[])if(x?.name&&!out.some(y=>y.name===x.name))out.push(x);for(const e of a.playerExtras||[])if(e.player&&!out.some(x=>x.name===e.player))out.push({name:e.player,role:'companion'});return out}
function extraPlayer(id,selected=''){let a=t(id).account,people=peopleList(a);modal(`${modalNav("openBilliard('"+id+"')",'Partida')}<h2>➕ Consumo extra personal</h2><p>Asigna cualquier producto directamente a una persona. No se mezcla con el consumo de la ronda.</p><div class="extraPersonBox"><label>¿Quién pidió el extra?</label><div class="personChips">${people.map(x=>`<button class="${selected===x.name?'selectedPerson':''}" onclick="extraPlayer('${id}','${esc(x.name)}')">${x.role==='player'?'🎱':'👤'} ${x.name}</button>`).join('')}</div><button class="wide" onclick="newPerson('${id}')">＋ Agregar persona / acompañante</button></div>${selected?`<div class="extraSelected"><b>Cuenta de ${selected}</b><span>${COP(playerMap(a)[selected]||0)}</span></div><div class="card inner extraCart">${extraItems(a,id,selected)}</div><input class="search" id="extraSearch" placeholder="🔎 Buscar cualquier producto…" oninput="renderExtraProducts('${id}','${esc(selected)}')"><div id="extraBox" class="products"></div>`:`<div class="notice compact">Selecciona una persona o agrega un acompañante para empezar.</div>`}`);if(selected)renderExtraProducts(id,selected)}
function newPerson(id){modal(`${modalNav("extraPlayer('"+id+"')",'Extras')}<h2>👤 Agregar persona</h2><div class="field"><label>Nombre</label><input id="personName" placeholder="Ej. Esposa de Juan"></div><div class="field"><label>Tipo</label><select id="personRole"><option value="companion">Acompañante (no participa como perdedor)</option><option value="player">Jugador</option></select></div><button class="gold wide" onclick="savePerson('${id}')">Agregar y continuar</button>`)}
function savePerson(id){let a=t(id).account,n=personName.value.trim(),role=personRole.value;if(!n)return alert('Escribe el nombre.');a.people||=[];if(!a.people.some(x=>x.name===n))a.people.push({name:n,role});if(role==='player'&&!a.players.includes(n))a.players.push(n);a.history.push(stamp()+` · ${role==='player'?'Jugador':'Acompañante'} agregado: ${n}`);save('Persona agregada');extraPlayer(id,n)}
function extraItems(a,id,name){let xs=(a.playerExtras||[]).filter(e=>e.player===name);return xs.length?xs.map(e=>`<div class="orderLine"><div><b>${e.name}</b><small>${COP(e.price)} c/u</small></div><div class="qtyCtl"><button class="mini" onclick="changeExtraQty('${id}','${esc(name)}','${e.id}',-1)">−</button><b>${e.qty}</b><button class="mini" onclick="changeExtraQty('${id}','${esc(name)}','${e.id}',1)">+</button><strong>${COP(e.price*e.qty)}</strong></div></div>`).join(''):'<div class="emptyOrder">Sin extras todavía. Elige cualquier producto abajo.</div>'}
function renderExtraProducts(id,name){let q=(document.getElementById('extraSearch')?.value||'').toLowerCase(),box=document.getElementById('extraBox');if(!box)return;box.innerHTML=catalog.filter(p=>p.price>0&&p.name.toLowerCase().includes(q)).slice(0,40).map(p=>`<div class="prod"><button onclick="addPlayerExtra('${id}','${p.id}','${esc(name)}')"><b>${simpleName(p.name)}</b><br>${COP(p.price)}</button></div>`).join('')}
function addPlayerExtra(id,pid,name){let a=t(id).account,p=catalog.find(x=>x.id===pid),it=(a.playerExtras||=[]).find(x=>x.player===name&&x.id===pid);it?it.qty++:a.playerExtras.push({id:pid,player:name,name:simpleName(p.name),price:p.price,qty:1,ts:new Date().toISOString()});consumeInventory(p);a.history.push(stamp()+` · Extra ${simpleName(p.name)} asignado a ${name}`);save(`Extra de ${name}`);extraPlayer(id,name)}
function changeExtraQty(id,name,pid,delta){let a=t(id).account,it=(a.playerExtras||[]).find(x=>x.player===name&&x.id===pid),p=catalog.find(x=>x.id===pid);if(delta>0){if(!it)return;it.qty++;if(p)consumeInventory(p)}else if(it){it.qty--;if(p)restoreInventory(p);if(it.qty<=0)a.playerExtras=a.playerExtras.filter(x=>x!==it)}a.history.push(stamp()+` · Ajuste extra ${name}: ${delta>0?'+1':'-1'} ${p?simpleName(p.name):pid}`);save('Ajuste extra personal');extraPlayer(id,name)}
function playerAccount(id,name){let a=t(id).account,m=playerMap(a),rounds=(a.rounds||[]).map((r,i)=>({r,i})).filter(x=>x.r.loser===name),extras=(a.playerExtras||[]).filter(e=>e.player===name),pays=(a.payments||[]).filter(p=>p.player===name);modal(`${modalNav("viewAccount('"+id+"')",'Cuenta')}<h2>👤 ${name}</h2><div class="total">Saldo: ${COP(m[name]||0)}</div><h3>Partidas perdidas</h3>${rounds.length?rounds.map(x=>`<div class="item"><span>Partida ${x.i+1}<br><small>${x.r.items.map(i=>`${i.name} ×${i.qty}`).join(' · ')||'Sin consumo'}</small></span><span><b>${COP(GAME+roundConsumption(x.r))}</b><br><button class="mini" onclick="editRound('${id}',${x.i})">✏️ Editar</button></span></div>`).join(''):'<small>Ninguna.</small>'}<h3>Extras personales</h3>${extras.length?extras.map((e,i)=>`<div class="item"><span>${e.name} ×${e.qty}</span><span><b>${COP(e.price*e.qty)}</b><br><button class="mini" onclick="removeExtra('${id}','${esc(name)}','${e.id}')">− Quitar 1</button></span></div>`).join(''):'<small>Sin extras.</small>'}<h3>Pagos</h3>${pays.length?pays.map(p=>`<div class="item"><span>${p.method}<br><small>${new Date(p.ts).toLocaleString('es-CO')}</small></span><b>− ${COP(p.amount)}</b></div>`).join(''):'<small>Sin pagos.</small>'}<button class="wide" onclick="extraPlayer('${id}')">➕ Agregar extra</button>${(m[name]||0)>0?`<button class="gold wide" onclick="payPlayer('${id}','${esc(name)}')">💰 Cobrar a ${name}</button>`:''}`)}
function restoreInventory(p,qty=1){if(p.recipe?.length){for(const r of p.recipe)S.inventory[r.productId]=(S.inventory[r.productId]||0)+r.qty*qty}else if(p.type==='stock')S.inventory[p.id]=(S.inventory[p.id]||0)+qty}
function removeExtra(id,name,pid){let a=t(id).account,i=a.playerExtras.findIndex(x=>x.player===name&&x.id===pid);if(i<0)return;let e=a.playerExtras[i],p=catalog.find(x=>x.id===pid);e.qty--;if(p)restoreInventory(p);if(e.qty<=0)a.playerExtras.splice(i,1);a.history.push(stamp()+` · Ajuste extra de ${name}: -1 ${e.name}`);save('Ajuste extra');playerAccount(id,name)}
function editRound(id,idx){let a=t(id).account,r=a.rounds[idx],known=[...new Set([...(a.players||[]),...a.rounds.map(x=>x.loser)])];modal(`${modalNav("viewAccount('"+id+"')",'Cuenta')}<h2>✏️ Editar partida ${idx+1}</h2><div class="field"><label>Perdedor</label><input id="editLoser" list="editPlayers" value="${r.loser}"><datalist id="editPlayers">${known.map(n=>`<option value="${n}">`).join('')}</datalist></div><h3>Productos</h3>${r.items.length?r.items.map((it,j)=>`<div class="item"><span>${it.name}</span><span><button class="mini" onclick="roundQty('${id}',${idx},${j},-1)">−</button> <b>${it.qty}</b> <button class="mini" onclick="roundQty('${id}',${idx},${j},1)">+</button></span></div>`).join(''):'<small>Sin productos</small>'}<button class="gold wide" onclick="saveRoundEdit('${id}',${idx})">Guardar perdedor</button><p class="notice compact">Los ajustes quedan registrados en el historial.</p>`)}
function saveRoundEdit(id,idx){let a=t(id).account,r=a.rounds[idx],n=editLoser.value.trim();if(!n)return alert('Indica el perdedor.');let old=r.loser;r.loser=n;a.players=[...new Set([...(a.players||[]),n])];a.people=a.people||[];if(!a.people.some(x=>x.name===n))a.people.push({name:n,role:'player'});a.history.push(stamp()+` · Partida ${idx+1}: perdedor cambiado ${old} → ${n}`);save('Corrección de partida');viewAccount(id)}
function roundQty(id,idx,j,delta){let a=t(id).account,r=a.rounds[idx],it=r.items[j],p=catalog.find(x=>x.id===it.id);if(delta<0&&it.qty<=0)return;if(delta>0){it.qty++;if(p)consumeInventory(p)}else{it.qty--;if(p)restoreInventory(p);if(it.qty<=0)r.items.splice(j,1)}a.history.push(stamp()+` · Ajuste partida ${idx+1}: ${it.name} ${delta>0?'+1':'-1'}`);save('Ajuste producto partida');editRound(id,idx)}
function pay(id){let x=t(id),a=x.account;if(x.type==='billar'){let m=playerMap(a),names=Object.keys(m).filter(n=>m[n]>0);if(!names.length)return alert('No hay saldos pendientes.');modal(`${modalNav("openAccount('"+id+"')",'Orden')}<h2>💰 Cobrar por jugador</h2><p>Selecciona quién paga. Cada jugador puede usar un método diferente.</p>${names.map(n=>`<button class="playerPay" onclick="payPlayer('${id}','${esc(n)}')"><span>👤 ${n}</span><b>${COP(m[n])}</b></button>`).join('')}<div class="total">Saldo total: ${COP(closedTotal(a))}</div>`);return}let v=closedTotal(a);payWhole(id,v)}
function payPlayer(id,name){let a=t(id).account,v=playerMap(a)[name]||0;if(v<=0)return;modal(`${modalNav("viewAccount('"+id+"')",'Cuenta')}<h2>💰 Cobrar a ${name}</h2><div class="total">${COP(v)}</div><div class="field"><label>Método</label><select id="method" onchange="payFields(${v})"><option>Efectivo</option><option>Transferencia</option><option>Mixto</option></select></div><div id="payFields"></div><div class="field"><label>Referencia / observación</label><input id="reference"></div><button class="gold wide" onclick="confirmPlayerPay('${id}','${esc(name)}',${v})">Confirmar pago</button>`);payFields(v)}
function payWhole(id,v){modal(`${modalNav("openAccount('"+id+"')",'Orden')}<h2>💰 Cobrar</h2><div class="total">${COP(v)}</div><div class="field"><label>Método</label><select id="method" onchange="payFields(${v})"><option>Efectivo</option><option>Transferencia</option><option>Mixto</option></select></div><div id="payFields"></div><div class="field"><label>Referencia</label><input id="reference"></div><button class="gold wide" onclick="confirmPay('${id}',${v})">Confirmar pago</button>`);payFields(v)}
function payFields(v){let el=document.getElementById('payFields'),m=document.getElementById('method').value;el.innerHTML=m==='Mixto'?`<div class="row"><div class="field"><label>Efectivo</label><input id="cashIn" type="number" value="${Math.floor(v/2)}"></div><div class="field"><label>Transferencia</label><input id="transIn" type="number" value="${v-Math.floor(v/2)}"></div></div>`:''}
function paymentParts(v){let m=method.value,c=m==='Efectivo'?v:m==='Mixto'?+cashIn.value:0,tr=m==='Transferencia'?v:m==='Mixto'?+transIn.value:0;return{m,c,tr}}
function confirmPlayerPay(id,name,v){let x=t(id),a=x.account,{m,c,tr}=paymentParts(v);if(c+tr!==v)return alert('Los pagos deben sumar el total.');let p={id:'LH-'+String(S.sales.length+1).padStart(6,'0'),ts:new Date().toISOString(),table:x.name,group:a.group,waitress:a.waitress,player:name,total:v,amount:v,cash:c,transfer:tr,method:m,ref:reference.value,account:JSON.parse(JSON.stringify(a))};a.payments||=[];a.payments.push({player:name,amount:v,cash:c,transfer:tr,method:m,ref:reference.value,ts:p.ts});S.sales.push(p);a.history.push(stamp()+` · Pago de ${name}: ${COP(v)} (${m})`);save(`Pago ${name}`);if(closedTotal(a)<=0&&!pendingTotal(a)){if(confirm('Todos los saldos están pagados. ¿Cerrar y liberar la mesa?'))x.account=null;save('Mesa liberada')}receipt(p)}
function confirmPay(id,v){let x=t(id),m=method.value,c=m==='Efectivo'?v:m==='Mixto'?+cashIn.value:0,tr=m==='Transferencia'?v:m==='Mixto'?+transIn.value:0;if(c+tr!==v)return alert('Los pagos deben sumar el total.');let sale={id:'LH-'+String(S.sales.length+1).padStart(6,'0'),ts:new Date().toISOString(),table:x.name,group:x.account.group,waitress:x.account.waitress,total:v,cash:c,transfer:tr,method:m,ref:reference.value,account:JSON.parse(JSON.stringify(x.account))};S.sales.push(sale);x.account=null;save(`Pago ${sale.id} ${x.name}`);receipt(sale)}
function receipt(p){modal(`<div class="receipt"><h2>🎱 Billares La Herradura Club</h2><b>Recibo ${p.id}</b><p>${new Date(p.ts).toLocaleString('es-CO')}<br>${p.table} · ${p.group}${p.player?'<br>Jugador: <b>'+p.player+'</b>':''}<br>Mesera: ${p.waitress}</p><hr><div class="total">TOTAL ${COP(p.total)}</div><p>${p.method}${p.ref?'<br>Ref: '+p.ref:''}</p><h2 class="green">PAGADO ✓</h2></div><button class="gold wide noPrint" onclick="window.print()">🖨️ Imprimir</button><button class="wide noPrint" onclick="showTables('billar');closeModal()">Volver a mesas</button>`)}
function move(id){let f=t(id),free=S.tables.filter(x=>!x.account);if(f.type==='billar'&&pendingTotal(f.account)>0)return alert('Termina o asigna la partida actual antes de trasladar la cuenta.');modal(`${modalNav("openAccount('${id}')",'Orden')}<h2>⇄ Trasladar cuenta</h2><p>${f.account.group} · ${COP(closedTotal(f.account))}</p><div class="field"><label>Mesa destino</label><select id="dest">${free.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select></div><p class="notice compact">Se conservan saldo, partidas, jugadores, consumos e historial.</p><button class="gold wide" onclick="confirmMove('${id}')">Confirmar traslado</button>`)}
function confirmMove(id){let f=t(id),d=t(dest.value);f.account.history.push(stamp()+` · Traslado ${f.name} → ${d.name}`);d.account=f.account;if(d.type==='billar'&&!d.account.activeRound)d.account.activeRound=newRound('Nueva partida tras traslado');if(d.type==='consumo')d.account.activeRound=null;f.account=null;save(`Traslado ${f.name} a ${d.name}`);closeModal();showTables(d.type)}
function openCustomer(id){window.open(`customer.html?table=${encodeURIComponent(id)}`,'cliente_'+id)}
function renderInventory(){if(!catalog.length)return;let q=(invSearch?.value||'').toLowerCase();inv.innerHTML=`<table><tr><th>Producto</th><th>Existencia</th><th>Venta</th></tr>${catalog.filter(p=>p.type==='stock'&&p.name.toLowerCase().includes(q)).map(p=>`<tr><td>${simpleName(p.name)}<br><small>${p.category}</small></td><td class="${(S.inventory[p.id]||0)<0?'red':''}">${S.inventory[p.id]||0}</td><td>${COP(p.price)}</td></tr>`).join('')}</table>`}
function renderSales(){salesList.innerHTML=S.sales.slice().reverse().map(x=>`<div class="item"><span>${x.id}<br><small>${x.waitress} · ${x.table}</small></span><b>${COP(x.total)}</b></div>`).join('')||'Sin ventas todavía.'}
function addExpense(){let n=expenseName.value.trim(),v=+expenseValue.value;if(!n||!v)return;S.expenses.push({name:n,value:v,ts:new Date().toISOString()});save(`Gasto ${n}`);expenseName.value='';expenseValue.value='';renderExpenses()}
function renderExpenses(){expenseList.innerHTML=S.expenses.slice().reverse().map(x=>`<div class="item"><span>${x.name}<br><small>${new Date(x.ts).toLocaleString('es-CO')}</small></span><b>${COP(x.value)}</b></div>`).join('')}
function startShift(){let name=prompt('Nombre de la mesera / responsable del turno:');if(!name)return;S.waitresses.includes(name)||S.waitresses.push(name);S.shifts.push({id:Date.now(),name,start:new Date().toISOString(),closed:false});save(`Turno abierto ${name}`);renderShift()}
function shiftClose(){let open=S.shifts.filter(x=>!x.closed);if(!open.length)return alert('No hay turno abierto.');let s=open[open.length-1];s.closed=true;s.end=new Date().toISOString();s.inventory=JSON.parse(JSON.stringify(S.inventory));save(`Cierre turno ${s.name}`);renderShift();alert('Cierre guardado. El inventario actual queda como entrega al siguiente turno.')}
function renderShift(){let open=S.shifts.filter(x=>!x.closed).slice(-1)[0];shiftInfo.innerHTML=open?`<p class="green">Turno abierto: <b>${open.name}</b><br>${new Date(open.start).toLocaleString('es-CO')}</p>`:'<p>No hay turno abierto.</p>'}
function renderReports(){let rev=S.sales.reduce((s,x)=>s+x.total,0),exp=S.expenses.reduce((s,x)=>s+x.value,0);monthly.innerHTML=`<div class="kpis"><div class="card kpi"><small>Ingresos</small><strong>${COP(rev)}</strong></div><div class="card kpi"><small>Egresos</small><strong>${COP(exp)}</strong></div><div class="card kpi"><small>Resultado preliminar</small><strong>${COP(rev-exp)}</strong></div><div class="card kpi"><small>Ventas</small><strong>${S.sales.length}</strong></div></div>`;let map={};for(const s of S.sales){let m=map[s.waitress]||(map[s.waitress]={total:0,mich:0,products:{}});m.total+=s.total;let items=[...(s.account.loose||[]),...(s.account.rounds||[]).flatMap(r=>r.items||[])];for(const i of items){m.products[i.name]=(m.products[i.name]||0)+i.qty;if(i.name.toLowerCase().includes('michel'))m.mich+=i.qty}}waitressReport.innerHTML=Object.entries(map).sort((a,b)=>b[1].total-a[1].total).map(([n,m],i)=>`<div class="item"><span>${i===0?'🏆 ':''}<b>${n}</b><br><small>Micheladas: ${m.mich} · ${Object.values(m.products).reduce((a,b)=>a+b,0)} productos</small></span><b>${COP(m.total)}</b></div>`).join('')||'Aún no hay ventas registradas.'}
function downloadBackup(){let b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='la-herradura-respaldo-v4-1.json';a.click()}
const modalEl=document.getElementById('modal'),payFieldsEl=document.getElementById('payFields')||{};renderHome();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
