const COP=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0);
const KEY='lhAdminV4', OLD='lhAdminV3', GAME=2000; let catalog=[];
let S=JSON.parse(localStorage.getItem(KEY)||'null')||migrate(JSON.parse(localStorage.getItem(OLD)||'null'))||init();
function init(){return{version:4,tables:[...Array(4)].map((_,i)=>({id:'B'+(i+1),type:'billar',name:'Billar '+(i+1),account:null})).concat([...Array(18)].map((_,i)=>({id:'C'+(i+1),type:'consumo',name:'Consumo '+(i+1),account:null}))),sales:[],expenses:[],shifts:[],inventory:{},waitresses:['Mesera turno 1','Mesera turno 2'],audit:[]}}
function migrate(o){if(!o)return null;o.version=4;o.audit=o.audit||[];for(const x of o.tables||[]){if(x.account&&x.type==='billar'){let a=x.account;a.rounds=a.rounds||[];for(const g of a.games||[])a.rounds.push({id:Date.now()+Math.random(),status:'closed',loser:g.loser||'Sin identificar',items:g.items||[],gameFee:GAME,createdAt:new Date().toISOString(),closedAt:new Date().toISOString()});a.games=[];a.activeRound=a.activeRound||{id:Date.now()+Math.random(),status:'active',items:[],createdAt:new Date().toISOString(),source:'Nueva partida'};a.players=a.players||[]}}return o}
function save(note){if(note)S.audit.push({ts:new Date().toISOString(),note});localStorage.setItem(KEY,JSON.stringify(S));renderHome()}
function stamp(){return new Date().toLocaleString('es-CO')};function t(id){return S.tables.find(x=>x.id===id)}
fetch('catalog.json').then(r=>r.json()).then(x=>{catalog=x;for(const p of catalog)if(S.inventory[p.id]==null)S.inventory[p.id]=p.stock;save();renderInventory()});
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='inventory')renderInventory();if(id==='sales')renderSales();if(id==='reports')renderReports();if(id==='expenses')renderExpenses();if(id==='shifts')renderShift()}
function modal(h){sheet.innerHTML=h;modalEl.classList.add('show')}function closeModal(){modalEl.classList.remove('show')}
function roundConsumption(r){return(r?.items||[]).reduce((s,i)=>s+i.price*i.qty,0)}
function closedTotal(a){return(a?.rounds||[]).reduce((s,r)=>s+GAME+roundConsumption(r),0)+(a?.loose||[]).reduce((s,i)=>s+i.price*i.qty,0)}
function pendingTotal(a){return roundConsumption(a?.activeRound)}
function displayTotal(a,type){return closedTotal(a)+(type==='billar'?pendingTotal(a):0)}
function renderHome(){let today=new Date().toDateString(),p=S.sales.filter(x=>new Date(x.ts).toDateString()===today);kSales.textContent=COP(p.reduce((s,x)=>s+x.total,0));kCash.textContent=COP(p.reduce((s,x)=>s+x.cash,0));kTransfer.textContent=COP(p.reduce((s,x)=>s+x.transfer,0));kOpen.textContent=S.tables.filter(x=>x.account).length;status.innerHTML=`<p>🎱 ${S.tables.filter(x=>x.type==='billar'&&x.account).length}/4 mesas de billar activas</p><p>🍺 ${S.tables.filter(x=>x.type==='consumo'&&x.account).length}/18 mesas de consumo activas</p><p>📦 ${catalog.filter(p=>(S.inventory[p.id]||0)<=5&&p.type==='stock').length} productos con existencia ≤ 5</p>`}
function showTables(type){showView('tablesView');tablesTitle.textContent=type==='billar'?'🎱 Mesas de billar':'🍺 Mesas de consumo';tables.innerHTML=S.tables.filter(x=>x.type===type).map(x=>`<div class="card tableCard ${x.account?'busy':''}"><span class="pill">${x.account?(type==='billar'?'EN JUEGO':'ABIERTA'):'DISPONIBLE'}</span><h3>${x.name}</h3><div>${x.account?x.account.group:'Libre'}</div><div class="amt">${x.account?COP(displayTotal(x.account,x.type)):'—'}</div>${x.account?`<div class="actions"><button class="primary" onclick="openAccount('${x.id}')">Gestionar</button>${x.type==='billar'?`<button onclick="openCustomer('${x.id}')">📺 Cliente</button>`:''}<button onclick="move('${x.id}')">⇄</button><button class="gold" onclick="pay('${x.id}')">Cobrar</button></div>`:`<button onclick="newAccount('${x.id}')">+ Abrir cuenta</button>`}</div>`).join('')}
function newAccount(id){modal(`<h2>Abrir ${t(id).name}</h2><div class="field"><label>Cliente / grupo</label><input id="group" placeholder="Ej. Carlos y amigos"></div><div class="field"><label>Mesera</label><select id="waitress">${S.waitresses.map(x=>`<option>${x}</option>`).join('')}</select></div><button class="gold wide" onclick="confirmOpen('${id}')">Abrir cuenta</button>`)}
function confirmOpen(id){let x=t(id);x.account={group:group.value||'Cliente',waitress:waitress.value,rounds:[],activeRound:x.type==='billar'?newRound('Nueva partida'):null,loose:[],history:[stamp()+' · Cuenta abierta'],players:[]};save(`Cuenta abierta ${x.name}`);closeModal();openAccount(id)}
function newRound(source='Nueva partida',items=[]){return{id:Date.now()+Math.random(),status:'active',items:items.map(i=>({...i})),createdAt:new Date().toISOString(),source}}
function openAccount(id){let x=t(id),a=x.account;if(x.type==='billar')openBilliard(id);else openConsumption(id)}
function openBilliard(id){let x=t(id),a=x.account,r=a.activeRound||newRound();a.activeRound=r;let n=(a.rounds?.length||0)+1;modal(`<div class="accountHead"><div><small>${x.name} · ${a.group}</small><h2>🎱 Partida ${n}</h2><span class="state activeState">● EN CURSO</span></div><div class="roundMoney"><small>Consumo ronda</small><strong>${COP(roundConsumption(r))}</strong></div></div><div class="notice compact">Los productos se acumulan en esta ronda. Al terminar, consumo + ${COP(GAME)} se asignan al perdedor.</div><div class="quickActions"><button class="finish" onclick="finishRound('${id}')">🏁 Terminar partida</button><button onclick="duplicatePreview('${id}')" ${a.rounds.length?'':'disabled'}>🔁 Duplicar anterior</button><button onclick="openCustomer('${id}')">📺 Vista cliente</button></div><div class="chips">${categoryButtons(id)}</div><input class="search" id="prodSearch" placeholder="🔎 Buscar producto…" oninput="renderProducts('${id}')"><div id="productBox" class="products"></div><h3>Ronda actual</h3><div class="card inner">${roundItems(r,id)}</div><h3>Cuentas acumuladas</h3><div class="card inner">${playerBalances(a)}</div><h3>Historial de partidas</h3><div class="card inner">${roundHistory(a)}</div><div class="stickyActions"><button onclick="move('${id}')">⇄ Cambiar mesa</button><button onclick="viewAccount('${id}')">🧾 Ver cuenta</button><button class="gold" onclick="pay('${id}')">💰 Cobrar</button></div>`);renderProducts(id)}
function openConsumption(id){let x=t(id),a=x.account;modal(`<h2>🍺 ${x.name} · ${a.group}</h2><p>Mesera: <b>${a.waitress}</b></p><div class="total">${COP(closedTotal(a))}</div><div class="chips">${categoryButtons(id)}</div><input class="search" id="prodSearch" placeholder="🔎 Buscar producto…" oninput="renderProducts('${id}')"><div id="productBox" class="products"></div><h3>Consumos</h3><div class="card inner">${looseItems(a)}</div><div class="stickyActions"><button onclick="move('${id}')">⇄ Cambiar mesa</button><button onclick="viewAccount('${id}')">🧾 Ver cuenta</button><button class="gold" onclick="pay('${id}')">💰 Cobrar</button></div>`);renderProducts(id)}
let activeCategory='Todos';function categoryButtons(id){let cats=['Todos','CERVEZAS','CUBETAZOS','MICHELADAS','GASEOSAS','LICORES','OTROS'];return cats.map(c=>`<button onclick="setCat('${id}','${c}')">${c==='Todos'?'⭐':c==='CERVEZAS'?'🍺':c==='CUBETAZOS'?'🪣':c==='MICHELADAS'?'🍹':c==='GASEOSAS'?'🥤':c==='LICORES'?'🥃':'🍬'} ${c}</button>`).join('')}
function setCat(id,c){activeCategory=c;renderProducts(id)}
function simpleName(n){return n.replace(/\s+[xX]\d+.*$/,'').replace(/\s+\d+\s*(cc|c|ml).*$/i,'').replace('Buweiser','Budweiser').trim()}
function catMatch(p,c){let z=p.category.toUpperCase(),n=p.name.toUpperCase();if(c==='Todos')return true;if(c==='CERVEZAS')return z.includes('CERVEZA');if(c==='CUBETAZOS')return z.includes('CUBET');if(c==='MICHELADAS')return z.includes('MICHEL')||n.includes('MICHEL');if(c==='GASEOSAS')return z.includes('GASEOSA')||z.includes('ENERG');if(c==='LICORES')return z.includes('AGUARD')||z.includes('LICOR')||z.includes('WHISK')||z.includes('RON');if(c==='OTROS')return !['CERVEZAS','CUBETAZOS','MICHELADAS','GASEOSAS','LICORES'].some(x=>catMatch(p,x));return true}
function renderProducts(id){let q=(prodSearch?.value||'').toLowerCase();let arr=catalog.filter(p=>p.price>0&&p.name.toLowerCase().includes(q)&&catMatch(p,activeCategory)).slice(0,36);productBox.innerHTML=arr.map(p=>`<div class="prod"><button onclick="addProduct('${id}','${p.id}')"><b>${simpleName(p.name)}</b><br><span>${COP(p.price)}</span></button></div>`).join('')||'<p>No hay productos en esta categoría.</p>'}
function consumeInventory(p,qty=1){if(p.recipe?.length){for(const r of p.recipe)S.inventory[r.productId]=(S.inventory[r.productId]||0)-r.qty*qty}else if(p.type==='stock')S.inventory[p.id]=(S.inventory[p.id]||0)-qty}
function addProduct(id,pid){let x=t(id),a=x.account,p=catalog.find(z=>z.id===pid);if(x.type==='billar'){let r=a.activeRound||(a.activeRound=newRound());let it=r.items.find(z=>z.id===pid);it?it.qty++:r.items.push({id:pid,name:simpleName(p.name),price:p.price,qty:1,addedAt:new Date().toISOString(),extra:r.source.startsWith('Duplicada')});}else{let it=a.loose.find(z=>z.id===pid);it?it.qty++:a.loose.push({id:pid,name:simpleName(p.name),price:p.price,qty:1,addedAt:new Date().toISOString()})}consumeInventory(p);a.history.push(stamp()+' · '+simpleName(p.name));save(`Producto ${simpleName(p.name)} en ${x.name}`);openAccount(id)}
function roundItems(r,id){return r.items.length?r.items.map(i=>`<div class="item"><span>${i.extra?'➕ ':''}${i.name} × ${i.qty}<br><small>${i.addedAt?new Date(i.addedAt).toLocaleTimeString('es-CO',{hour:'numeric',minute:'2-digit'}):''}</small></span><b>${COP(i.price*i.qty)}</b></div>`).join(''):'<small>Aún no hay productos en esta ronda.</small>'}
function looseItems(a){return a.loose.length?a.loose.map(i=>`<div class="item"><span>${i.name} × ${i.qty}</span><b>${COP(i.price*i.qty)}</b></div>`).join(''):'<small>Sin consumos.</small>'}
function finishRound(id){let x=t(id),a=x.account,r=a.activeRound;if(!r)return;let known=[...new Set((a.rounds||[]).map(z=>z.loser))];modal(`<h2>🏁 Terminar partida ${(a.rounds?.length||0)+1}</h2><p>Consumo: <b>${COP(roundConsumption(r))}</b><br>Chico: <b>${COP(GAME)}</b><br>Total a asignar: <b class="goldText">${COP(roundConsumption(r)+GAME)}</b></p><div class="field"><label>¿Quién perdió?</label><input id="loserName" list="players" placeholder="Nombre del perdedor"><datalist id="players">${known.map(n=>`<option value="${n}">`).join('')}</datalist></div><button class="finish wide" onclick="confirmFinish('${id}')">Confirmar y asignar cuenta</button><button class="wide" onclick="openBilliard('${id}')">Cancelar</button>`)}
function confirmFinish(id){let x=t(id),a=x.account,n=loserName.value.trim();if(!n)return alert('Debes identificar al perdedor.');let r=a.activeRound;r.status='closed';r.loser=n;r.gameFee=GAME;r.closedAt=new Date().toISOString();a.rounds.push(r);a.players=[...new Set([...(a.players||[]),n])];a.history.push(stamp()+` · Partida ${a.rounds.length} asignada a ${n}: ${COP(roundConsumption(r)+GAME)}`);a.activeRound=newRound('Nueva partida');save(`Partida ${a.rounds.length} de ${x.name} asignada a ${n}`);openBilliard(id)}
function duplicatePreview(id){let a=t(id).account,last=a.rounds[a.rounds.length-1];if(!last)return;modal(`<h2>🔁 Duplicar partida anterior</h2><p>Se copiará únicamente el pedido. <b>No se copiará el perdedor.</b></p><div class="card inner">${last.items.map(i=>`<div class="item"><span>${i.name} × ${i.qty}</span><b>${COP(i.price*i.qty)}</b></div>`).join('')||'Sin productos'}</div><div class="total">Pedido: ${COP(roundConsumption(last))}</div><p class="notice compact">Al confirmar, estas unidades se descuentan del inventario como un nuevo despacho. Después podrás agregar extras.</p><button class="gold wide" onclick="confirmDuplicate('${id}')">Duplicar pedido</button><button class="wide" onclick="openBilliard('${id}')">Cancelar</button>`)}
function confirmDuplicate(id){let a=t(id).account,last=a.rounds[a.rounds.length-1];if(!last)return;let items=last.items.map(i=>({...i,addedAt:new Date().toISOString(),extra:false}));for(const i of items){let p=catalog.find(z=>z.id===i.id);if(p)consumeInventory(p,i.qty)}a.activeRound=newRound(`Duplicada de partida ${a.rounds.length}`,items);a.history.push(stamp()+` · Pedido de partida ${a.rounds.length} duplicado`);save(`Partida duplicada en ${t(id).name}`);openBilliard(id)}
function playerBalances(a){let m={};for(const r of a.rounds||[])m[r.loser]=(m[r.loser]||0)+GAME+roundConsumption(r);return Object.keys(m).length?Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="item"><span>👤 <b>${n}</b></span><b>${COP(v)}</b></div>`).join(''):'<small>Aún no hay cuentas asignadas.</small>'}
function roundHistory(a){return(a.rounds||[]).length?[...a.rounds].reverse().map((r,i)=>`<div class="item"><span>Partida ${a.rounds.indexOf(r)+1} · <b>${r.loser}</b><br><small>${r.items.map(x=>`${x.name} ×${x.qty}`).join(' · ')||'Sin consumo'}</small></span><b>${COP(GAME+roundConsumption(r))}</b></div>`).join(''):'<small>Sin partidas finalizadas.</small>'}
function viewAccount(id){let x=t(id),a=x.account;modal(`<h2>🧾 Cuenta · ${x.name}</h2><p>${a.group} · Mesera: ${a.waitress}</p>${x.type==='billar'?`<h3>Por jugador</h3>${playerBalances(a)}<h3>Partidas</h3>${roundHistory(a)}${pendingTotal(a)?`<div class="notice">Hay una ronda en curso con ${COP(pendingTotal(a))} de consumo aún sin perdedor.</div>`:''}`:`${looseItems(a)}`}<div class="total">Total asignado: ${COP(closedTotal(a))}</div><button class="wide" onclick="openAccount('${id}')">Volver</button>`)}
function move(id){let f=t(id),free=S.tables.filter(x=>!x.account);if(f.type==='billar'&&pendingTotal(f.account)>0)return alert('Termina o asigna la partida actual antes de trasladar la cuenta.');modal(`<h2>⇄ Trasladar cuenta</h2><p>${f.account.group} · ${COP(closedTotal(f.account))}</p><div class="field"><label>Mesa destino</label><select id="dest">${free.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select></div><p class="notice compact">Se conservan saldo, partidas, jugadores, consumos e historial.</p><button class="gold wide" onclick="confirmMove('${id}')">Confirmar traslado</button>`)}
function confirmMove(id){let f=t(id),d=t(dest.value);f.account.history.push(stamp()+` · Traslado ${f.name} → ${d.name}`);d.account=f.account;if(d.type==='billar'&&!d.account.activeRound)d.account.activeRound=newRound('Nueva partida tras traslado');if(d.type==='consumo')d.account.activeRound=null;f.account=null;save(`Traslado ${f.name} a ${d.name}`);closeModal();showTables(d.type)}
function pay(id){let x=t(id),a=x.account;if(x.type==='billar'&&pendingTotal(a)>0)return alert('Hay una partida en curso con consumo pendiente. Termínala y asigna el perdedor antes de cobrar.');let v=closedTotal(a);modal(`<h2>💰 Cobrar ${x.name}</h2><div class="total">${COP(v)}</div><div class="field"><label>Método</label><select id="method" onchange="payFields(${v})"><option>Efectivo</option><option>Transferencia</option><option>Mixto</option></select></div><div id="payFields"></div><div class="field"><label>Referencia / observación</label><input id="reference"></div><button class="gold wide" onclick="confirmPay('${id}',${v})">Confirmar pago</button>`);payFields(v)}
function payFields(v){let m=method.value;payFieldsEl.innerHTML=m==='Mixto'?`<div class="row"><div class="field"><label>Efectivo</label><input id="cashIn" type="number" value="${Math.floor(v/2)}"></div><div class="field"><label>Transferencia</label><input id="transIn" type="number" value="${v-Math.floor(v/2)}"></div></div>`:''}
function confirmPay(id,v){let x=t(id),m=method.value,c=m==='Efectivo'?v:m==='Mixto'?+cashIn.value:0,tr=m==='Transferencia'?v:m==='Mixto'?+transIn.value:0;if(c+tr!==v)return alert('Los pagos deben sumar el total.');let sale={id:'LH-'+String(S.sales.length+1).padStart(6,'0'),ts:new Date().toISOString(),table:x.name,group:x.account.group,waitress:x.account.waitress,total:v,cash:c,transfer:tr,method:m,ref:reference.value,account:JSON.parse(JSON.stringify(x.account))};S.sales.push(sale);x.account=null;save(`Pago ${sale.id} ${x.name}`);receipt(sale)}
function receipt(p){modal(`<div class="receipt"><h2>🎱 Billares La Herradura Club</h2><b>Recibo ${p.id}</b><p>${new Date(p.ts).toLocaleString('es-CO')}<br>${p.table} · ${p.group}<br>Mesera: ${p.waitress}</p><hr>${p.account.rounds?.length?playerBalances(p.account):''}<hr><div class="total">TOTAL ${COP(p.total)}</div><p>${p.method}${p.ref?'<br>Ref: '+p.ref:''}</p><h2 class="green">PAGADO ✓</h2></div><button class="gold wide noPrint" onclick="window.print()">🖨️ Imprimir</button>`)}
function openCustomer(id){window.open(`customer.html?table=${encodeURIComponent(id)}`,'cliente_'+id)}
function renderInventory(){if(!catalog.length)return;let q=(invSearch?.value||'').toLowerCase();inv.innerHTML=`<table><tr><th>Producto</th><th>Existencia</th><th>Venta</th></tr>${catalog.filter(p=>p.type==='stock'&&p.name.toLowerCase().includes(q)).map(p=>`<tr><td>${simpleName(p.name)}<br><small>${p.category}</small></td><td class="${(S.inventory[p.id]||0)<0?'red':''}">${S.inventory[p.id]||0}</td><td>${COP(p.price)}</td></tr>`).join('')}</table>`}
function renderSales(){salesList.innerHTML=S.sales.slice().reverse().map(x=>`<div class="item"><span>${x.id}<br><small>${x.waitress} · ${x.table}</small></span><b>${COP(x.total)}</b></div>`).join('')||'Sin ventas todavía.'}
function addExpense(){let n=expenseName.value.trim(),v=+expenseValue.value;if(!n||!v)return;S.expenses.push({name:n,value:v,ts:new Date().toISOString()});save(`Gasto ${n}`);expenseName.value='';expenseValue.value='';renderExpenses()}
function renderExpenses(){expenseList.innerHTML=S.expenses.slice().reverse().map(x=>`<div class="item"><span>${x.name}<br><small>${new Date(x.ts).toLocaleString('es-CO')}</small></span><b>${COP(x.value)}</b></div>`).join('')}
function startShift(){let name=prompt('Nombre de la mesera / responsable del turno:');if(!name)return;S.waitresses.includes(name)||S.waitresses.push(name);S.shifts.push({id:Date.now(),name,start:new Date().toISOString(),closed:false});save(`Turno abierto ${name}`);renderShift()}
function shiftClose(){let open=S.shifts.filter(x=>!x.closed);if(!open.length)return alert('No hay turno abierto.');let s=open[open.length-1];s.closed=true;s.end=new Date().toISOString();s.inventory=JSON.parse(JSON.stringify(S.inventory));save(`Cierre turno ${s.name}`);renderShift();alert('Cierre guardado. El inventario actual queda como entrega al siguiente turno.')}
function renderShift(){let open=S.shifts.filter(x=>!x.closed).slice(-1)[0];shiftInfo.innerHTML=open?`<p class="green">Turno abierto: <b>${open.name}</b><br>${new Date(open.start).toLocaleString('es-CO')}</p>`:'<p>No hay turno abierto.</p>'}
function renderReports(){let rev=S.sales.reduce((s,x)=>s+x.total,0),exp=S.expenses.reduce((s,x)=>s+x.value,0);monthly.innerHTML=`<div class="kpis"><div class="card kpi"><small>Ingresos</small><strong>${COP(rev)}</strong></div><div class="card kpi"><small>Egresos</small><strong>${COP(exp)}</strong></div><div class="card kpi"><small>Resultado preliminar</small><strong>${COP(rev-exp)}</strong></div><div class="card kpi"><small>Ventas</small><strong>${S.sales.length}</strong></div></div>`;let map={};for(const s of S.sales){let m=map[s.waitress]||(map[s.waitress]={total:0,mich:0,products:{}});m.total+=s.total;let items=[...(s.account.loose||[]),...(s.account.rounds||[]).flatMap(r=>r.items||[])];for(const i of items){m.products[i.name]=(m.products[i.name]||0)+i.qty;if(i.name.toLowerCase().includes('michel'))m.mich+=i.qty}}waitressReport.innerHTML=Object.entries(map).sort((a,b)=>b[1].total-a[1].total).map(([n,m],i)=>`<div class="item"><span>${i===0?'🏆 ':''}<b>${n}</b><br><small>Micheladas: ${m.mich} · ${Object.values(m.products).reduce((a,b)=>a+b,0)} productos</small></span><b>${COP(m.total)}</b></div>`).join('')||'Aún no hay ventas registradas.'}
function downloadBackup(){let b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='la-herradura-respaldo-v4.json';a.click()}
const modalEl=document.getElementById('modal'),payFieldsEl=document.getElementById('payFields')||{};renderHome();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
