/* La Herradura Admin v4.19.42 - Extensión aislada de rondas para Consumo. */
(function(){
'use strict';
const drafts={};
const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ensure=a=>{a.consumptionRounds ||= [];a.consumptionDraft ||= [];};
const total=items=>(items||[]).reduce((s,i)=>s+(+i.price||0)*(+i.qty||0),0);
const due=(a,name)=>Math.max(0,a.consumptionRounds.filter(r=>r.payer===name).reduce((s,r)=>s+total(r.items),0)-(a.payments||[]).filter(p=>p.player===name).reduce((s,p)=>s+p.amount,0));
const names=a=>[...new Set((a.consumptionRounds||[]).map(r=>r.payer).filter(Boolean))];
const state=id=>(drafts[id] ||= {requester:'',payer:''});
const baseOpen=window.openConsumption,baseAdd=window.addProduct,baseQty=window.consumptionQty,basePay=window.pay,baseView=window.viewAccount,baseReceiptDetail=window.receiptDetail;
const baseProducts=window.renderProducts;
window.renderProducts=function(id){
 if(t(id)?.type!=='consumo')return baseProducts(id);
 const a=t(id).account;ensure(a);
 const q=(document.getElementById('prodSearch')?.value||'').toLowerCase();
 const arr=catalog.filter(p=>p.price>0&&p.name.toLowerCase().includes(q)&&catMatch(p,activeCategory)).slice(0,36);
 const el=document.getElementById('productBox');if(!el)return;
 el.innerHTML=arr.map(p=>{const qty=a.consumptionDraft.find(z=>z.id===p.id)?.qty||0;return `<div class="prod ${qty?'prodSelected':''}"><button onclick="addProduct('${id}','${p.id}')"><b>${html(simpleName(p.name))}</b>${qty?`<span class="prodQty">×${qty}</span>`:''}<br><span>${COP(p.price)}</span>${qty?'<small class="selectedLabel">✓ Seleccionado</small>':''}</button></div>`}).join('')||'<p>No hay productos en esta categoría.</p>';
};

window.consumptionWho=(id,key,val)=>{state(id)[key]=val};
window.openConsumption=function(id){baseOpen(id);const x=t(id),a=x.account;ensure(a);const box=document.querySelector('.consumptionManage');if(!box)return;const s=state(id),pending=total(a.consumptionDraft),rounds=a.consumptionRounds;
const panel=document.createElement('section');panel.className='card inner consumoRoundPanel';panel.innerHTML=`<h3>👥 Identificación de la ronda ${rounds.length+1}</h3><p class="muted">Antes de guardar, identifica quién solicita y quién paga. Los siguientes pedidos de esa persona se suman a su cuenta.</p><div class="row"><div class="field"><label>¿Quién solicita?</label><input id="consumoRequester" list="consumoPeople" value="${html(s.requester)}" placeholder="Ej. Juan" oninput="consumptionWho('${id}','requester',this.value)"></div><div class="field"><label>¿Quién paga?</label><input id="consumoPayer" list="consumoPeople" value="${html(s.payer)}" placeholder="Ej. Pedro" oninput="consumptionWho('${id}','payer',this.value)"></div></div><datalist id="consumoPeople">${[...new Set(rounds.flatMap(r=>[r.requester,r.payer]))].map(n=>`<option value="${html(n)}"></option>`).join('')}</datalist><div class="notice compact">Pedido actual sin guardar: <b>${COP(pending)}</b> · ${a.consumptionDraft.length} producto(s) distinto(s). Las rondas guardadas no se vuelven a cargar al inventario.</div><h3>📋 Rondas guardadas (${rounds.length})</h3>${rounds.length?rounds.map((r,i)=>`<div class="item"><span>Ronda ${i+1} · Pide: <b>${html(r.requester)}</b><br>Paga: <b>${html(r.payer)}</b> · ${r.items.reduce((n,it)=>n+it.qty,0)} unidades</span><b>${COP(total(r.items))}</b></div>`).join(''):'<p class="muted">Aún no hay rondas guardadas.</p>'}<h3>💳 Cuentas individuales</h3>${names(a).length?names(a).map(n=>`<div class="item"><span>👤 ${html(n)} · ${rounds.filter(r=>r.payer===n).length} rondas a pagar · ${rounds.filter(r=>r.requester===n).length} solicitadas</span><b>${COP(due(a,n))}</b></div>`).join(''):'<p class="muted">Se mostrarán al guardar la primera ronda.</p>'}`;
const order=box.querySelector('.orderPanel');if(order){order.parentNode.insertBefore(panel,order);const title=order.querySelector('.orderTitle h3');if(title)title.textContent='🧾 Productos de la ronda actual';const sub=order.querySelector('.orderTitle strong');if(sub)sub.textContent=COP(pending);const cart=order.querySelector('.orderCart');if(cart)cart.innerHTML=consumptionDraftItems(a,id)}
};
function consumptionDraftItems(a,id){return a.consumptionDraft.length?a.consumptionDraft.map(i=>`<div class="orderLine"><div><b>${html(i.name)}</b><small>${COP(i.price)} c/u</small></div><div class="qtyCtl"><button class="mini" onclick="consumptionQty('${id}','${i.id}',-1)">−</button><b>${i.qty}</b><button class="mini" onclick="consumptionQty('${id}','${i.id}',1)">+</button><strong>${COP(i.price*i.qty)}</strong></div></div>`).join(''):'<div class="emptyOrder">Selecciona los productos de esta nueva ronda.</div>'}
window.addProduct=function(id,pid){const x=t(id);if(x?.type!=='consumo')return baseAdd(id,pid);const a=x.account;ensure(a);const p=catalog.find(z=>z.id===pid);if(!p)return;let it=a.consumptionDraft.find(z=>z.id===pid);it?it.qty++:a.consumptionDraft.push({id:pid,name:simpleName(p.name),price:p.price,cost:unitCost(p),qty:1});baseAdd(id,pid)};
window.consumptionQty=function(id,pid,delta){const a=t(id).account;ensure(a);let it=a.consumptionDraft.find(z=>z.id===pid);if(!it)return alert('Solo puedes modificar productos de la ronda actual.');if(delta<0&&it.qty<=0)return;const p=catalog.find(z=>z.id===pid),agg=a.loose.find(z=>z.id===pid);if(!agg)return;it.qty+=delta;if(it.qty<=0)a.consumptionDraft=a.consumptionDraft.filter(z=>z!==it);agg.qty+=delta;if(agg.qty<=0)a.loose=a.loose.filter(z=>z!==agg);if(p){if(delta>0)consumeInventory(p);else restoreInventory(p)}a.history.push(stamp()+' · Ajuste ronda consumo '+pid+' '+delta);save('Ajuste ronda consumo');openConsumption(id)};
window.saveConsumptionOrder=function(id){const a=t(id).account;ensure(a);const s=state(id),requester=s.requester.trim(),payer=s.payer.trim();if(!a.consumptionDraft.length)return alert('Agrega al menos un producto para guardar la ronda.');if(!requester||!payer)return alert('Identifica quién solicita y quién paga esta ronda.');const items=a.consumptionDraft.map(i=>({...i}));a.consumptionRounds.push({id:'CR-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),requester,payer,items,ts:new Date().toISOString(),waitress:a.waitress});a.consumptionDraft=[];drafts[id]={requester,payer};a.history.push(stamp()+` · Ronda ${a.consumptionRounds.length}: solicita ${requester}, paga ${payer}, ${COP(total(items))}`);save('Ronda de consumo guardada');alert('✓ Ronda '+a.consumptionRounds.length+' guardada a nombre de '+payer);openConsumption(id)};
window.consumoRoundAccounts=function(id){const a=t(id).account;ensure(a);const pending=total(a.consumptionDraft);return `<h3>👥 Rondas y cuentas por persona</h3>${a.consumptionRounds.map((r,i)=>`<div class="item"><span>Ronda ${i+1}: ${html(r.requester)} solicitó · paga ${html(r.payer)}<br>${r.items.map(z=>html(z.name)+' ×'+z.qty).join(', ')}</span><b>${COP(total(r.items))}</b></div>`).join('')||'<p>Sin rondas guardadas.</p>'}${names(a).map(n=>`<div class="item"><span>👤 ${html(n)} · ${a.consumptionRounds.filter(r=>r.requester===n).length} solicitadas / ${a.consumptionRounds.filter(r=>r.payer===n).length} a pagar</span><b>${COP(due(a,n))}</b></div>`).join('')}${pending?`<div class="notice">Ronda sin guardar: ${COP(pending)}</div>`:''}`};
window.viewAccount=function(id){if(t(id)?.type!=='consumo')return baseView(id);baseView(id);const a=t(id).account;ensure(a);const target=document.querySelector('#sheet .total');if(target)target.insertAdjacentHTML('beforebegin',consumoRoundAccounts(id));};
window.pay=function(id){const x=t(id);if(x?.type!=='consumo')return basePay(id);const a=x.account;ensure(a);if(a.consumptionDraft.length)return alert('Primero guarda la ronda actual identificando quién solicita y quién paga.');const v=closedTotal(a);if(v<=0)return alert('No hay saldo pendiente.');const individual=names(a).filter(n=>due(a,n)>0);const assigned=individual.reduce((s,n)=>s+due(a,n),0);const legacy=Math.max(0,v-assigned);modal(`${modalNav("openAccount('"+id+"')",'Orden')}<h2>💰 Cobrar mesa de consumo</h2><p>Selecciona una persona o cobra la mesa completa.</p><button class="gold wide" onclick="payWhole('${id}',${v})">💳 Pago total · ${COP(v)}</button>${individual.length?`<h3>Cuentas por persona</h3>${individual.map(n=>`<button class="playerPay" onclick="consumoPayPerson('${id}',${JSON.stringify(n).replace(/"/g,'&quot;')})"><span>👤 ${html(n)} · ${a.consumptionRounds.filter(r=>r.payer===n).length} rondas</span><b>${COP(due(a,n))}</b></button>`).join('')}`:''}${legacy?`<p class="notice">${COP(legacy)} corresponden a consumos anteriores sin responsable asignado o ajustes/devoluciones. Pueden cobrarse con Pago total.</p>`:''}<div class="total">Saldo pendiente: ${COP(v)}</div>`)};
window.consumoPayPerson=function(id,name){const a=t(id).account;if((a.returns||[]).length)return alert('Esta cuenta tiene devoluciones: por seguridad concilia el saldo mediante Pago total antes de cobrar por persona.');const v=due(a,name);if(v<=0)return alert('Esta persona no tiene saldo.');modal(`${modalNav("pay('"+id+"')",'Cobros')}<h2>💰 Cobrar a ${html(name)}</h2><p>${a.consumptionRounds.filter(r=>r.payer===name).length} rondas asignadas</p><div class="total">${COP(v)}</div><div class="field"><label>Método</label><select id="method" onchange="payFields(${v})"><option>Efectivo</option><option>Transferencia</option><option>Mixto</option></select></div><div id="payFields"></div><div class="field"><label>Referencia / observación</label><input id="reference"></div><button class="gold wide" onclick="consumoConfirmPerson('${id}',${JSON.stringify(name).replace(/"/g,'&quot;')})">Confirmar pago</button>`);payFields(v)};
window.consumoConfirmPerson=function(id,name){const x=t(id),a=x.account,v=due(a,name),parts=paymentParts(v),err=validatePayment(v,parts);if(err)return alert(err);if(!v)return alert('Saldo ya pagado.');const items=a.consumptionRounds.filter(r=>r.payer===name).flatMap(r=>r.items),cogs=items.reduce((s,i)=>s+itemUnitCost(i)*i.qty,0);const prev=(a.payments||[]).filter(p=>p.player===name).reduce((s,p)=>s+(p.cogs||0),0);const cost=Math.max(0,cogs-prev);const ts=new Date().toISOString();const snapshot=JSON.parse(JSON.stringify(a));const sale={id:'LH-'+String(S.sales.length+1).padStart(6,'0'),ts,table:x.name,group:a.group,waitress:a.waitress,player:name,total:v,cash:parts.c,transfer:parts.tr,cashReceived:parts.received,change:parts.change,method:parts.m,ref:document.getElementById('reference')?.value||'',cogs:cost,grossProfit:v-cost,account:snapshot};a.payments||=[];a.payments.push({player:name,amount:v,cash:parts.c,transfer:parts.tr,ts,cogs:cost});S.sales.push(sale);a.history.push(stamp()+` · Pago de ${name}: ${COP(v)}`);save('Pago consumo por persona');if(closedTotal(a)<=0&&confirm('Cuenta saldada. ¿Liberar la mesa?')){x.account=null;save('Mesa liberada')}receipt(sale)};
window.receiptDetail=function(sale){if(sale.player&&sale.account?.consumptionRounds){const items=sale.account.consumptionRounds.filter(r=>r.payer===sale.player).flatMap(r=>r.items);return `<div class="receiptDetail"><h3>Rondas de ${html(sale.player)}</h3>${receiptItems(items).map(i=>`<div class="item"><span>${html(i.name)} ×${i.qty}</span><b>${COP(i.price*i.qty)}</b></div>`).join('')}</div>`}return baseReceiptDetail(sale)};
})();
