/* Personal y Turnos — módulo piloto independiente v4.19.40.
   Almacenamiento local en este navegador. NO es autenticación multiusuario segura. */
(function(){
'use strict';
const K='lhTurnosPilot1';
const now=()=>new Date().toISOString();
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{let d=JSON.parse(localStorage.getItem(K));if(d&&Array.isArray(d.staff)&&Array.isArray(d.turns))return d}catch(e){}return {staff:[],turns:[],log:[]}};
let D=read(),session=null;
function persist(){localStorage.setItem(K,JSON.stringify(D));render()}
function active(){return D.turns.findLast?D.turns.findLast(x=>x.status==='open'):D.turns.slice().reverse().find(x=>x.status==='open')}
function pending(){return D.turns.slice().reverse().find(x=>x.status==='pending')}
function number(id){let el=document.getElementById(id);return el?Number(el.value):NaN}
function field(id){return (document.getElementById(id)?.value||'').trim()}
function validMoney(n){return Number.isFinite(n)&&n>=0&&n<=1000000000}
function salesBetween(a,b){return (((typeof S!=='undefined')?S:null)?.sales||[]).filter(x=>x.ts&&x.ts>=a&&x.ts<=b).reduce((z,x)=>({cash:z.cash+(Number(x.cash)||0),transfer:z.transfer+(Number(x.transfer)||0),total:z.total+(Number(x.total)||0)}),{cash:0,transfer:0,total:0})}
function expectedCash(t,end){const sales=salesBetween(t.start,end);const wage=Number(t.wage)||0;return {sales,wage,expected:t.base+sales.cash-wage}}
function shiftSales(t,end){return (((typeof S!=='undefined')?S:null)?.sales||[]).filter(x=>x.ts&&x.ts>=t.start&&x.ts<=end)}
function salesSummary(t,end){const rows=shiftSales(t,end),byTable={billar:0,consumo:0},byStaff={};for(const x of rows){const type=String(x.table||'').toLowerCase().includes('billar')?'billar':'consumo';byTable[type]+=Number(x.total)||0;const n=x.waitress||'Sin identificar';byStaff[n]=(byStaff[n]||0)+(Number(x.total)||0)}return {count:rows.length,byTable,byStaff}}
function reportHTML(t,end){const r=expectedCash(t,end),detail=salesSummary(t,end);return `<div class="tnReport"><h3>🧾 Reporte de caja · ${t.kind===1?'día':'noche'}</h3><p>Mesera: <b>${esc(nameOf(t.staffId))}</b></p><p>Base recibida: <b>${money(t.base)}</b></p><p>Cobros registrados: <b>${detail.count}</b> · venta total: <b>${money(r.sales.total)}</b></p><p>Ventas de mesas de billar (cobros): <b>${money(detail.byTable.billar)}</b></p><p>Ventas de mesas de consumo (cobros): <b>${money(detail.byTable.consumo)}</b></p><p>Pagos en efectivo: <b>${money(r.sales.cash)}</b></p><p>Transferencias (no se cuentan en caja): <b>${money(r.sales.transfer)}</b></p><p>Pago del turno en efectivo: <b>−${money(r.wage)}</b></p><p><b>EFECTIVO ESPERADO: ${money(r.expected)}</b></p><p class="tnMuted">Este primer reporte agrupa cobros registrados, no partidas ni unidades individuales. Los gastos generales y devoluciones requieren conciliación adicional. Las ventas sin cobro aún no forman parte del total.</p></div>`}

function note(action){D.log.push({at:now(),action});if(D.log.length>300)D.log.shift()}
function nameOf(id){return D.staff.find(x=>x.id===id)?.name||'Sin identificar'}
function logged(){if(!session){alert('Inicia sesión en Personal y Turnos.');return false}return true}
function admin(){if(!session||session.role!=='admin'){alert('Esta operación corresponde a la administradora.');return false}return true}
function setSession(id,pin){const u=D.staff.find(x=>x.id===id&&x.pin===pin&&x.active!==false);if(!u){alert('Usuario o clave incorrectos.');return}session={id:u.id,role:u.role,name:u.name};render()}
window.tnLogin=()=>setSession(field('tnUser'),field('tnPass'));
window.tnLogout=()=>{session=null;render()};
// Recuperación exclusiva del piloto local: conserva personal, turnos y datos comerciales.
// NO habilitar este mecanismo en una versión con autenticación real.
window.tnResetPilotAdmin=()=>{
  if(session)return alert('Cierra sesión del módulo antes de recuperar el acceso.');
  const admins=D.staff.filter(x=>x.role==='admin');
  if(admins.length!==1)return alert('No se puede recuperar automáticamente este registro.');
  const phrase=field('tnResetConfirm');
  const newPin=field('tnResetPass');
  if(phrase!=='REINICIAR')return alert('Escribe REINICIAR para confirmar el cambio de clave de prueba.');
  if(newPin.length<6)return alert('La nueva clave de prueba debe tener al menos 6 caracteres.');
  if(!confirm('¿Cambiar únicamente la clave de la administradora local? No se borrarán mesas, ventas, inventario, meseras ni turnos. Esta opción NO es segura para uso real.'))return;
  admins[0].pin=newPin;
  note('Recuperación de clave de administración del piloto local');
  persist();
  alert('Clave de prueba cambiada. Ya puedes iniciar sesión.');
};
window.tnTogglePassword=id=>{const el=document.getElementById(id);if(el)el.type=el.type==='password'?'text':'password'};
const passControl=(id,autocomplete='off')=>`<div class="tnPassword"><input id="${id}" type="password" autocomplete="${autocomplete}" autocapitalize="off" spellcheck="false"><button type="button" class="tnEye" onclick="tnTogglePassword('${id}')" aria-label="Mostrar u ocultar clave">👁️ Ver</button></div>`;

window.tnBootstrap=()=>{if(D.staff.length)return;let name=field('tnAdminName'),pin=field('tnAdminPass');if(name.length<2||pin.length<6)return alert('Indica nombre y una clave de al menos 6 caracteres.');D.staff.push({id:'admin-'+Date.now(),name,role:'admin',pin,active:true});note('Se creó la cuenta de administración local');persist();alert('Administradora registrada en este dispositivo. Inicia sesión para continuar.')};
window.tnCreateStaff=()=>{if(!admin())return;let name=field('tnStaffName'),pin=field('tnStaffPass');if(name.length<2||pin.length<6)return alert('Escribe nombre y clave de al menos 6 caracteres.');if(D.staff.some(x=>x.name.toLowerCase()===name.toLowerCase()))return alert('Ya existe ese nombre.');D.staff.push({id:'staff-'+Date.now(),name,role:'waitress',pin,active:true});note('Administración registró a '+name);persist()};
window.tnOpen=()=>{if(!logged())return;if(active()||pending())return alert('Hay un turno abierto o pendiente de entrega.');let base=number('tnBase'),kind=field('tnKind');if(!validMoney(base))return alert('Indica una base válida.');if(kind==='1'&&session.role!=='admin')return alert('La base del primer turno la registra la administradora.');if(kind==='2')return alert('El segundo turno debe iniciarse desde la recepción de caja del primero.');let who=field('tnAssigned');if(!who||!D.staff.some(x=>x.id===who&&x.role==='waitress'))return alert('Selecciona la mesera que recibe.');D.turns.push({id:'turn-'+Date.now(),kind:1,staffId:who,openedBy:session.id,start:now(),base,baseNotes:field('tnOpenNotes'),status:'open'});note('Apertura turno día · '+nameOf(who)+' · base '+money(base));persist()};
window.tnSaveWage=()=>{if(!logged())return;const t=active();if(!t)return alert('No hay turno abierto.');if(session.id!==t.staffId&&session.role!=='admin')return alert('Solo la mesera responsable o administración puede registrar el pago.');const wage=number('tnWage');if(!validMoney(wage))return alert('Registra un pago válido.');if(wage>t.base+salesBetween(t.start,now()).cash)return alert('El pago excede el efectivo disponible.');t.wage=wage;note('Pago de turno registrado: '+money(wage));persist()};
window.tnClose=()=>{if(!logged())return;let t=active();if(!t)return alert('No hay turno abierto.');if(session.id!==t.staffId&&session.role!=='admin')return alert('Solo la mesera responsable o administración puede cerrar.');let counted=number('tnCounted'),obs=field('tnOutgoingNotes');if(!validMoney(counted))return alert('Indica cuánto dinero se contó.');let end=now(),calc=expectedCash(t,end),sales=calc.sales,expected=calc.expected;if(expected<0)return alert('El pago de turno excede el efectivo disponible. Verifica los valores.');
if(Math.abs(counted-expected)>0.01&&!obs)return alert('Hay una diferencia. Es obligatorio registrar observaciones.');
t.closedAt=end;t.sales=sales;t.salesDetail=salesSummary(t,end);t.expected=expected;t.outgoingCount=counted;t.outgoingNotes=obs;t.closedBy=session.id;t.status='pending';t.inventorySnapshot=JSON.parse(JSON.stringify(((typeof S!=='undefined')?S:null)?.inventory||{}));note('Cierre declarado · '+nameOf(t.staffId)+' · '+money(counted));persist()};
window.tnReceive=()=>{if(!logged())return;let t=pending();if(!t||t.kind!==1)return alert('No hay entrega del primer turno pendiente.');if(session.role!=='waitress')return alert('Debe ingresar la mesera que recibe.');if(session.id===t.staffId)return alert('La misma mesera no puede entregar y recibir.');let counted=number('tnReceived'),obs=field('tnIncomingNotes');if(!validMoney(counted))return alert('Registra el dinero recibido.');if((counted!==t.expected||counted!==t.outgoingCount)&&!obs)return alert('Si lo recibido difiere de lo esperado o de lo declarado por quien entrega, registra observaciones.');t.receivedCount=counted;t.receivedBy=session.id;t.receivedAt=now();t.incomingNotes=obs;t.status='completed';D.turns.push({id:'turn-'+Date.now(),kind:2,staffId:session.id,openedBy:session.id,start:now(),base:counted,fromTurn:t.id,status:'open'});note('Entrega verificada · '+nameOf(session.id)+' · '+money(counted));persist()};
window.tnFinal=()=>{if(!admin())return;let t=pending();if(!t||t.kind!==2)return alert('No hay cierre nocturno pendiente.');let counted=number('tnAdminCount'),obs=field('tnAdminNotes');if(!validMoney(counted))return alert('Indica el efectivo que recoge administración.');if(counted!==t.expected&&!obs)return alert('Registra observaciones por la diferencia.');t.receivedCount=counted;t.receivedBy=session.id;t.receivedAt=now();t.incomingNotes=obs;t.withdrawal=counted;t.status='completed';note('Cierre general · retiro administración '+money(counted)+' · saldo operativo $0');persist()};
function render(){let root=document.getElementById('turnosPanel');if(!root)return;let t=active(),p=pending(),options=D.staff.filter(x=>x.role==='waitress'&&x.active!==false).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');let latest=D.turns.slice(-12).reverse();
let h='<div class="tnCard"><span class="tnPill">Piloto local · v4.19.40</span><p class="tnMuted">Este módulo guarda datos únicamente en este navegador. Todavía NO bloquea Billar/Consumo ni sincroniza usuarios entre dispositivos. Las claves locales no son seguras para uso real: utiliza claves de prueba, no contraseñas personales.</p></div>';
if(!D.staff.length){h+=`<div class="tnCard"><h3>🔐 Registrar administradora (primera vez)</h3><label>Nombre</label><input id="tnAdminName" autocomplete="off"><label>Clave de prueba (mínimo 6 caracteres)</label>${passControl("tnAdminPass")}<p class="tnMuted">Escribe una clave de prueba que recuerdes. Si el iPhone propone una clave automática, puedes reemplazarla y usar 👁️ Ver para comprobarla.</p><button class="gold" onclick="tnBootstrap()">Crear administración local</button></div>`}
else if(!session){h+=`<div class="tnCard"><h3>🔐 Ingresar a Personal y Turnos</h3><label>Usuario</label><select id="tnUser">${D.staff.filter(x=>x.active!==false).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} (${x.role==='admin'?'Administración':'Mesera'})</option>`).join('')}</select><label>Clave</label>${passControl("tnPass")}<button class="gold" onclick="tnLogin()">Ingresar</button><details class="tnRecovery"><summary>🔑 ¿Olvidaste la clave de prueba?</summary><p class="tnMuted">Solo para esta versión piloto. Permite cambiar la clave local sin borrar ventas, inventario, personal ni historial de turnos. No usar como seguridad definitiva.</p><label>Escribe REINICIAR para confirmar</label><input id="tnResetConfirm" autocomplete="off" placeholder="REINICIAR"><label>Nueva clave de prueba (mínimo 6 caracteres)</label>${passControl("tnResetPass")}<button type="button" onclick="tnResetPilotAdmin()">Restablecer clave de prueba</button></details></div>`}
else{
h+=`<div class="tnCard tnInline"><b>👤 ${esc(session.name)}</b><span class="tnPill">${session.role==='admin'?'Administradora':'Mesera'}</span><button onclick="tnLogout()">Cerrar sesión del módulo</button></div>`;
if(session.role==='admin')h+=`<div class="tnGrid"><div class="tnCard"><h3>👥 Registrar mesera</h3><label>Nombre de la mesera</label><input id="tnStaffName" autocomplete="off"><label>Clave de prueba</label>${passControl("tnStaffPass")}<button class="gold" onclick="tnCreateStaff()">Guardar mesera</button><p class="tnMuted">Registradas: ${D.staff.filter(x=>x.role==='waitress').map(x=>esc(x.name)).join(', ')||'Ninguna'}</p></div>${!t&&!p?`<div class="tnCard"><h3>🌤️ Abrir primer turno</h3><label>Mesera que recibe</label><select id="tnAssigned"><option value="">Seleccionar...</option>${options}</select><label>Base entregada (COP)</label><input id="tnBase" type="number" min="0" step="1" placeholder="150000"><input id="tnKind" type="hidden" value="1"><label>Observaciones iniciales (opcional)</label><textarea id="tnOpenNotes" placeholder="Ej. base en billetes y monedas..."></textarea><button class="gold" onclick="tnOpen()">Abrir turno de día</button></div>`:''}</div>`;
if(t){let calc=expectedCash(t,now()),ss=calc.sales,expected=calc.expected;h+=`<div class="tnCard"><h3>🟢 Turno ${t.kind===1?'día':'noche'} abierto</h3><p>Responsable: <b>${esc(nameOf(t.staffId))}</b></p><p>Base recibida: <b>${money(t.base)}</b></p><p>Ventas efectivo registradas: <b>${money(ss.cash)}</b></p><p>Transferencias registradas: <b>${money(ss.transfer)}</b> <small>(no son efectivo)</small></p><p><b>EFECTIVO ESPERADO (calculado automáticamente):</b> <span class="tnNumber">${money(expected)}</span></p>${reportHTML(t,now())}<p class="tnMuted">El esperado es provisional: base + cobros en efectivo − pago del turno. Otros gastos y retiros todavía requieren conciliación.</p>${session.id===t.staffId||session.role==='admin'?`<label>Pago de este turno en efectivo (COP)</label><input id="tnWage" type="number" min="0" step="1" value="${Number(t.wage)||0}"><button onclick="tnSaveWage()">Guardar pago del turno y actualizar esperado</button><label>Efectivo físico contado por quien entrega (no modifica el esperado)</label><input id="tnCounted" type="number" min="0" step="1"><label>Observaciones y anomalías del turno</label><textarea id="tnOutgoingNotes" placeholder="Faltantes, sobrantes, inventario, novedades... "></textarea><button class="gold" onclick="tnClose()">Cerrar turno y preparar entrega</button>`:''}</div>`}
if(p){h+=`<div class="tnCard"><h3>📋 Entrega pendiente · turno ${p.kind===1?'día':'noche'}</h3><p>Entrega: <b>${esc(nameOf(p.staffId))}</b></p><p>Esperado: <span class="tnNumber">${money(p.expected)}</span></p><p>Declarado por quien entrega: <b>${money(p.outgoingCount)}</b></p><p>Diferencia de salida frente al esperado: <b>${money(p.outgoingCount-p.expected)}</b> ${p.outgoingCount===p.expected?'✅ Exacto':p.outgoingCount>p.expected?'⬆️ Sobrante declarado':'⬇️ Faltante declarado'}</p><p>Observaciones de salida: ${esc(p.outgoingNotes||'Sin novedades registradas')}</p>${reportHTML(p,p.closedAt||now())}${p.kind===1&&session.role==='waitress'&&session.id!==p.staffId?`<label>Dinero físico contado por quien recibe (base real del siguiente turno)</label><p class="tnMuted">Compara tu conteo tanto con el efectivo esperado como con el valor declarado por la mesera saliente. Si hay diferencias, explica la novedad.</p><input id="tnReceived" type="number" min="0" step="1"><label>Observaciones de quien recibe</label><textarea id="tnIncomingNotes" placeholder="Verificación y anomalías..."></textarea><button class="gold" onclick="tnReceive()">Confirmar recepción y abrir noche</button>`:''}${p.kind===2&&session.role==='admin'?`<label>Efectivo recogido por administración</label><input id="tnAdminCount" type="number" min="0" step="1"><label>Observaciones de administración</label><textarea id="tnAdminNotes" placeholder="Verificación final..."></textarea><button class="gold" onclick="tnFinal()">Confirmar retiro total y cierre diario</button>`:''}</div>`}
if(latest.length)h+=`<div class="tnCard"><h3>📚 Historial de entregas</h3>${latest.map(x=>`<div class="tnLog"><b>${x.kind===1?'Día':'Noche'} · ${esc(nameOf(x.staffId))}</b> <span class="tnPill">${x.status==='open'?'Abierto':x.status==='pending'?'Pendiente':'Completado'}</span><p class="tnMuted">${new Date(x.start).toLocaleString('es-CO')} · base ${money(x.base)}</p>${x.expected!=null?`<p>Pago de turno: ${money(x.wage||0)} · esperado: ${money(x.expected)} · declarado: ${money(x.outgoingCount)} · recibido: ${x.receivedCount==null?'Pendiente':money(x.receivedCount)}</p><p>Diferencia recibido vs. esperado: <b>${x.receivedCount==null?'Pendiente':money(x.receivedCount-x.expected)}</b> · recibido vs. declarado: <b>${x.receivedCount==null?'Pendiente':money(x.receivedCount-x.outgoingCount)}</b></p><p>Observaciones: ${esc(x.outgoingNotes||'—')} / ${esc(x.incomingNotes||'—')}</p>`:''}</div>`).join('')}</div>`;
}
root.innerHTML=h;
}
const orig=window.renderShift;
window.renderShift=function(){if(typeof orig==='function'){try{orig()}catch(e){}}const legacy=document.getElementById('shiftInfo');if(legacy)legacy.style.display='none';render()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
