/* Personal y Turnos — módulo piloto independiente v4.19.47.
   Almacenamiento local en este navegador. NO es autenticación multiusuario segura. */
(function(){
'use strict';
const K='lhTurnosPilot1';
const now=()=>new Date().toISOString();
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{let d=JSON.parse(localStorage.getItem(K));if(d&&Array.isArray(d.staff)&&Array.isArray(d.turns))return d}catch(e){}return {staff:[],turns:[],log:[]}};
let D=read(),session=null,turnosScreen='inicio';
window.tnNavigate=(screen)=>{turnosScreen=screen;render();document.getElementById('turnosPanel')?.scrollIntoView({behavior:'smooth',block:'start'});};
function persist(){localStorage.setItem(K,JSON.stringify(D));render()}
function active(){return D.turns.findLast?D.turns.findLast(x=>x.status==='open'):D.turns.slice().reverse().find(x=>x.status==='open')}
function pending(){return D.turns.slice().reverse().find(x=>x.status==='pending')}
function number(id){let el=document.getElementById(id);return el?Number(el.value):NaN}
function field(id){return (document.getElementById(id)?.value||'').trim()}
function validMoney(n){return Number.isFinite(n)&&n>=0&&n<=1000000000}
function salesBetween(a,b){return (((typeof S!=='undefined')?S:null)?.sales||[]).filter(x=>x.ts&&x.ts>=a&&x.ts<=b).reduce((z,x)=>({cash:z.cash+(Number(x.cash)||0),transfer:z.transfer+(Number(x.transfer)||0),total:z.total+(Number(x.total)||0)}),{cash:0,transfer:0,total:0})}
function expectedCash(t,end){const sales=salesBetween(t.start,end);const wage=Number(t.wage)||0;return {sales,wage,expected:t.base+sales.cash-wage}}
function shiftSales(t,end){return (((typeof S!=='undefined')?S:null)?.sales||[]).filter(x=>x.ts&&x.ts>=t.start&&x.ts<=end)}
function salesSummary(t,end){const rows=shiftSales(t,end),byTable={billar:0,consumo:0},byStaff={};for(const x of rows){const type=String(x.table||'').toLowerCase().includes('billar')?'billar':'consumo';byTable[type]+=Number(x.total)||0;const n=x.waitress||'Sin identificar';byStaff[n]=(byStaff[n]||0)+(Number(x.total)||0)}return {count:rows.length,byTable,byStaff}}
function paidItems(s){
 const a=s.account||{},player=s.player,cons=String(s.table||'').toLowerCase().includes('consumo');
 if(cons&&Array.isArray(a.consumptionRounds)&&a.consumptionRounds.length){
  const rs=player?a.consumptionRounds.filter(r=>r.payer===player):a.consumptionRounds;
  return {items:rs.flatMap(r=>r.items||[]),games:0,warning:!player&&(a.payments||[]).some(p=>p.player)};
 }
 if(!cons){const rs=(a.rounds||[]).filter(r=>!player||r.loser===player);return {items:[...rs.flatMap(r=>r.items||[]),...(a.playerExtras||[]).filter(i=>!player||i.player===player),...(!player?(a.loose||[]):[])],games:rs.length,warning:false}}
 return {items:a.loose||[],games:0,warning:false};
}
function productReport(t,end){
 const sales=shiftSales(t,end),map=new Map();let games=0,warning=false;
 for(const sale of sales){const d=paidItems(sale);games+=d.games;warning ||=d.warning;for(const i of d.items){const k=String(i.id||i.name)+'|'+Number(i.price||0),r=map.get(k)||{name:i.name||i.id||'Producto',qty:0,total:0};r.qty+=Number(i.qty)||0;r.total+=(Number(i.qty)||0)*(Number(i.price)||0);map.set(k,r)}}
 return {products:[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'es')),games,warning};
}
function reportHTML(t,end){
 const r=expectedCash(t,end),detail=salesSummary(t,end),pr=productReport(t,end);
 const lines=pr.products.map(x=>`<tr><td>${esc(x.name)}</td><td style="text-align:right">${x.qty}</td><td style="text-align:right">${money(x.total)}</td></tr>`).join('');
 return `<div class="tnReport"><h3>🧾 Reporte de caja · ${t.kind===1?'día':'noche'}</h3><p>Mesera: <b>${esc(nameOf(t.staffId))}</b></p><p>Base recibida: <b>${money(t.base)}</b></p><p>Cobros registrados: <b>${detail.count}</b> · venta cobrada: <b>${money(r.sales.total)}</b></p><p>Billar (cobros): <b>${money(detail.byTable.billar)}</b> · Consumo (cobros): <b>${money(detail.byTable.consumo)}</b></p><p>Pagos en efectivo: <b>${money(r.sales.cash)}</b> · Transferencias: <b>${money(r.sales.transfer)}</b></p><p>Pago de turno: <b>−${money(r.wage)}</b></p><p><b>EFECTIVO ESPERADO: ${money(r.expected)}</b></p><h4>🎱 Partidas y productos asociados a cobros</h4><p>Partidas identificadas en comprobantes: <b>${pr.games}</b> · referencia ${money(pr.games*2000)} a $2.000</p><div style="overflow-x:auto"><table style="width:100%;font-size:.85rem"><thead><tr><th>Producto</th><th>Unidades</th><th>Valor</th></tr></thead><tbody>${lines||'<tr><td colspan="3">Sin productos identificados en cobros</td></tr>'}</tbody></table></div><p class="tnMuted">⚠️ Detalle informativo basado en fotografías de cuentas al cobrar, no en eventos de venta por unidad. En pagos parciales, devoluciones, ediciones o cobros repetidos puede haber duplicaciones. No usar como conciliación definitiva de stock ni como conteo certificado de partidas. El total de caja se calcula exclusivamente con cobros efectivos.</p></div>`;
}
function returnsForDay(day){
 let ledger=[];try{ledger=JSON.parse(localStorage.getItem('lhReturnLedger1')||'[]')}catch(e){}
 const rows=Array.isArray(ledger)?ledger.filter(r=>r.ts?.slice(0,10)===day).map(r=>({...r,waitressShare:(Number(r.credit)||0)/2,businessShare:(Number(r.credit)||0)/2})):[];
 const seen=new Set(rows.map(r=>r.id));const tables=(((typeof S!=='undefined')?S:null)?.tables||[]);
 for(const table of tables){for(const r of table.account?.returns||[]){if(r.ts?.slice(0,10)===day&&!seen.has(r.id)){rows.push({...r,table:table.name||table.id,waitressShare:(Number(r.credit)||0)/2,businessShare:(Number(r.credit)||0)/2});seen.add(r.id)}}}
 return rows;
}
function returnsHTML(dateKey){
 const rows=returnsForDay(dateKey),sum=k=>rows.reduce((n,r)=>n+(Number(r[k])||0),0);
 return `<details class="tnAdminSection"><summary>↩️ Devoluciones · reparto 50 % / 50 % (${rows.length})</summary><p>Valor total recibido por devoluciones: <b>${money(sum('credit'))}</b></p><p>Participación de meseras: <b>${money(sum('waitressShare'))}</b> · Participación del negocio: <b>${money(sum('businessShare'))}</b></p><div style="overflow-x:auto"><table class="tnAdminTable"><thead><tr><th>Producto / mesa</th><th>Unidades</th><th>Mesera</th><th>Negocio</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)} · ${esc(r.table)}<small> · ${esc(r.waitress||'')}</small></td><td>${Number(r.qty)||0}</td><td>${money(r.waitressShare)}</td><td>${money(r.businessShare)}</td></tr>`).join('')||'<tr><td colspan="4">Sin devoluciones visibles en cuentas abiertas</td></tr>'}</tbody></table></div><p class="tnMuted">Los valores de reparto son informativos: no se descuentan otra vez del efectivo sin un movimiento de pago registrado. Las nuevas devoluciones se guardan en un historial local independiente, incluso al cerrar la mesa. Las anteriores solo se recuperan si la cuenta sigue abierta. No se descuentan nuevamente del efectivo sin registrar su pago.</p></details>`;
}
function dateKey(ts){return String(ts||'').slice(0,10)}
function closeSnapshot(){
 const t=D.turns.filter(x=>x.expected!=null&&dateKey(x.start)===dateKey(now()));
 const sum=t.reduce((a,x)=>{a.cash+=Number(x.sales?.cash)||0;a.qr+=Number(x.sales?.transfer)||0;a.sales+=Number(x.sales?.total)||0;a.wages+=Number(x.wage)||0;return a},{cash:0,qr:0,sales:0,wages:0});
 const first=t.find(x=>x.kind===1),base=Number(first?.base)||0;
 const expenses=(D.adminExpenses||[]).filter(x=>dateKey(x.ts)===dateKey(now())).map(x=>({description:x.description,amount:x.amount}));
 const out=expenses.reduce((n,x)=>n+(Number(x.amount)||0),0);
 const map=new Map();let games=0;
 for(const x of t){const r=productReport(x,x.closedAt||now());games+=r.games;for(const item of r.products){const k=item.name,prev=map.get(k)||{name:k,qty:0,total:0};prev.qty+=item.qty;prev.total+=item.total;map.set(k,prev)}}
 const returns=returnsForDay(dateKey(now())).map(r=>({name:r.name,qty:r.qty,waitress:r.waitress,credit:r.credit,returnRate:r.returnRate,waitressShare:r.waitressShare,businessShare:r.businessShare}));
 return {id:'close-'+Date.now(),date:dateKey(now()),verifiedAt:now(),verifiedBy:session.name,turns:t.map(x=>({id:x.id,kind:x.kind,staff:nameOf(x.staffId),base:x.base,start:x.start,closedAt:x.closedAt,sales:{...x.sales},wage:x.wage,expected:x.expected,outgoingCount:x.outgoingCount,receivedCount:x.receivedCount,outgoingNotes:x.outgoingNotes,incomingNotes:x.incomingNotes})),...sum,base,expenses,out,products:[...map.values()],games,returns,expected:base+sum.cash-sum.wages-out,actual:Number(t.find(x=>x.kind===2)?.receivedCount)||0};
}
function snapshotHTML(c){const line=(label,v)=>`<div class="tnAdminLine"><span>${label}</span><b>${money(v)}</b></div>`;
return `<div class="tnCard tnAdminDaily"><h3>🧾 Cierre verificado · ${esc(c.date)}</h3><p>Verificado: ${esc(c.verifiedAt)} · ${esc(c.verifiedBy)}</p>${line('Total en ventas (efectivo + QR)',c.sales)}${line('Efectivo cobrado',c.cash)}${line('QR / transferencias',c.qr)}${line('Base inicial',c.base)}${line('Salarios',-c.wages)}${line('Gastos en efectivo',-c.out)}${line('Ingreso neto de ventas',c.sales-c.wages-c.out)}${line('Efectivo esperado',c.expected)}${line('Efectivo recibido',c.actual)}${line('Diferencia',c.actual-c.expected)}<h4>🎱 Servicios</h4><p>${c.games} tiempos identificados · ${money(c.games*2000)} (estimado)</p><h4>🍺 Productos vendidos (estimado)</h4><table class="tnAdminTable"><thead><tr><th>Producto</th><th>Cantidad</th><th>Valor</th></tr></thead><tbody>${(c.products||[]).map(r=>`<tr><td>${esc(r.name)}</td><td>${r.qty}</td><td>${money(r.total)}</td></tr>`).join('')}</tbody></table><h4>↩️ Devoluciones registradas al verificar</h4>${(c.returns||[]).map(r=>`<p>${esc(r.name)} ×${r.qty} · ${esc(r.waitress||'')} · recibido ${money(r.credit)} · mesera ${money(r.waitressShare)} · negocio ${money(r.businessShare)}</p>`).join('')||'<p>Sin devoluciones identificadas</p>'}<h4>🧾 Gastos</h4>${(c.expenses||[]).map(r=>`<p>${esc(r.description)}: ${money(r.amount)}</p>`).join('')||'<p>Sin gastos</p>'}<h4>👩‍💼 Turnos</h4>${(c.turns||[]).map(r=>`<p><b>${r.kind===1?'Día':'Noche'} · ${esc(r.staff)}</b> · base ${money(r.base)} · ventas ${money(r.sales?.total)} · salario ${money(r.wage)} · esperado ${money(r.expected)}<br>Observaciones: ${esc(r.outgoingNotes||'—')} / ${esc(r.incomingNotes||'—')}</p>`).join('')}<p class="tnMuted">Reporte de solo lectura. Productos, tiempos y devoluciones provienen de datos disponibles al verificar y pueden ser incompletos.</p></div>`;
}
window.tnPrintReport=(id,turnId)=>{if(!session)return;const c=(D.verifiedClosures||[]).find(x=>x.id===id);let html;if(c){if(session.role!=='admin')return;html=snapshotHTML(c)}else{const t=D.turns.find(x=>x.id===turnId);if(!t||t.expected==null||(session.role!=='admin'&&session.id!==t.staffId))return;html=t.reportSnapshot||reportHTML(t,t.closedAt||now())}const w=window.open('','_blank');if(!w)return alert('Permite ventanas emergentes para imprimir.');w.document.write('<!doctype html><html lang="es"><meta charset="utf-8"><title>Reporte La Herradura</title><style>body{font:15px Arial;padding:24px;color:#111}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ccc;padding:8px;text-align:left}.tnAdminLine{display:flex;justify-content:space-between;padding:6px;border-bottom:1px solid #ddd}button{display:none}</style><body><h1>La Herradura · Reporte de caja</h1>'+html+'</body></html>');w.document.close();w.focus();w.print()};
window.tnShowVerified=(id)=>{if(!admin())return;const c=(D.verifiedClosures||[]).find(x=>x.id===id),el=document.getElementById('tnVerifiedDetail');if(!c||!el)return;el.innerHTML=snapshotHTML(c)+`<button class="gold" onclick="tnPrintReport('${esc(c.id)}')">🖨️ Imprimir reporte</button>`};
function dailyHTML(){
 const day=new Date().toDateString(),turns=D.turns.filter(x=>new Date(x.start).toDateString()===day&&x.expected!=null);
 const unique=[...new Map(turns.map(t=>[t.id,t])).values()];
 const total=unique.reduce((a,t)=>{const v=t.sales||{cash:0,transfer:0,total:0};a.cash+=Number(v.cash)||0;a.transfer+=Number(v.transfer)||0;a.sales+=Number(v.total)||0;a.wages+=Number(t.wage)||0;return a},{cash:0,transfer:0,sales:0,wages:0});
 const expenses=(D.adminExpenses||[]).filter(x=>new Date(x.ts).toDateString()===day),out=expenses.reduce((n,x)=>n+(Number(x.amount)||0),0);
 const first=unique.find(t=>t.kind===1),last=unique.find(t=>t.kind===2),base=Number(first?.base)||0;
 const expected=base+total.cash-total.wages-out,net=total.sales-total.wages-out;
 // Cobros del turno son la fuente de verdad del dinero; los detalles de cuentas son orientativos.
 const map=new Map();let games=0,warning=false;
 for(const t of unique){const r=productReport(t,t.closedAt||now());games+=r.games;warning ||=r.warning;for(const i of r.products){const k=i.name;const row=map.get(k)||{name:k,qty:0,total:0};row.qty+=i.qty;row.total+=i.total;map.set(k,row)}}
 const products=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'es'));
 const productTotal=products.reduce((n,r)=>n+r.total,0),gameValue=games*2000;
 const actual=last&&last.receivedCount!=null?Number(last.receivedCount):null;
 const gap=actual===null?null:actual-expected;
 const card=(label,value,sub)=>`<div class="tnAdminMetric"><small>${label}</small><strong>${value}</strong><span>${sub}</span></div>`;
 return `<div class="tnCard tnAdminDaily"><div class="tnAdminHead"><div><h3>📊 Cierre general de administración</h3><p class="tnMuted">${esc(new Date().toLocaleDateString('es-CO',{day:'numeric',month:'long',year:'numeric'}))} · ${unique.length} turno(s) cerrado(s)</p></div><span class="tnPill">Solo administración</span></div>
 <div class="tnAdminMetrics">${card('VENTA DE PRODUCTOS IDENTIFICADOS',money(productTotal),products.reduce((n,r)=>n+r.qty,0)+' unidades · detalle estimado')}${card('TIEMPOS DE BILLAR IDENTIFICADOS',String(games),money(gameValue)+' a $2.000 c/u · estimado')}${card('INGRESOS POR QR / TRANSFERENCIA',money(total.transfer),'Pagos electrónicos registrados')}${card('INGRESOS EN EFECTIVO',money(total.cash),'Cobros físicos registrados')}</div>
 <details class="tnAdminSection"><summary>🍺 Ver productos y cantidades (${products.length})</summary><div style="overflow-x:auto"><table class="tnAdminTable"><thead><tr><th>Producto</th><th>Unidades</th><th>Valor estimado</th></tr></thead><tbody>${products.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.qty}</td><td>${money(r.total)}</td></tr>`).join('')||'<tr><td colspan="3">Sin productos identificados en cobros</td></tr>'}</tbody></table></div></details>
 <details class="tnAdminSection"><summary>🎱 Ver servicios de billar</summary><p>${games} partidas identificadas × $2.000 = <b>${money(gameValue)}</b></p><p class="tnMuted">Este conteo procede de comprobantes cobrados y no certifica todas las partidas jugadas.</p></details>
 <div class="tnAdminSection"><h4>💰 Resumen financiero del día</h4><div class="tnAdminLine"><span>Total en ventas (efectivo + QR)</span><b>${money(total.sales)}</b></div><div class="tnAdminLine"><span>Pago de turnos</span><b>−${money(total.wages)}</b></div><div class="tnAdminLine"><span>Gastos registrados en efectivo</span><b>−${money(out)}</b></div><div class="tnAdminLine tnAdminStrong"><span>Ingreso neto de ventas</span><b>${money(net)}</b></div><hr><div class="tnAdminLine"><span>Base inicial del primer turno</span><b>${money(base)}</b></div><div class="tnAdminLine"><span>+ Total en ventas</span><b>${money(total.sales)}</b></div><div class="tnAdminLine"><span>− Ingresos por QR / transferencia</span><b>−${money(total.transfer)}</b></div><div class="tnAdminLine"><span>− Salarios y gastos en efectivo</span><b>−${money(total.wages+out)}</b></div><div class="tnAdminLine tnAdminStrong"><span>Efectivo esperado en caja</span><b>${money(expected)}</b></div>${actual===null?'<p class="tnMuted">Aún no hay retiro final confirmado por administración.</p>':`<div class="tnAdminLine"><span>Efectivo retirado por administración</span><b>${money(actual)}</b></div><div class="tnAdminLine tnAdminStrong"><span>Diferencia de arqueo</span><b>${money(gap)}</b></div>`}</div>
 ${returnsHTML(dateKey(now()))}<details class="tnAdminSection"><summary>🧾 Registrar y consultar gastos</summary>${expenses.map(x=>`<p>${esc(x.description)} · ${money(x.amount)}</p>`).join('')||'<p class="tnMuted">Sin gastos registrados hoy.</p>'}<label>Concepto del gasto</label><input id="tnExpenseDescription" placeholder="Ej. elementos de aseo"><label>Valor pagado en efectivo (COP)</label><input id="tnExpenseAmount" type="number" min="0" step="1"><button onclick="tnAddExpense()">Registrar gasto del día</button></details>
 <p class="tnMuted">⚠️ Los totales monetarios de ventas provienen de cobros registrados; el desglose de productos y tiempos se reconstruye de las cuentas al cobrar. Pagos parciales, devoluciones o ediciones pueden duplicar u omitir cantidades: no es aún un kardex ni un conteo certificado. QR y transferencias se agrupan como pagos electrónicos. Los gastos registrados aquí se consideran pagados en efectivo y no descontados previamente. Si se registran gastos después del retiro de caja, se recalcula el esperado y puede cambiar la diferencia.</p></div>`;
}
window.tnAddExpense=()=>{if(!admin())return;if((D.verifiedClosures||[]).some(c=>c.date===dateKey(now())))return alert('El cierre de hoy está verificado y bloqueado.');const description=field('tnExpenseDescription'),amount=number('tnExpenseAmount');if(description.length<3||!validMoney(amount)||amount<=0)return alert('Escribe concepto y valor válido.');if(!confirm('¿Confirmas que este gasto salió en efectivo de la caja y no se descontó antes?'))return;D.adminExpenses||=[];D.adminExpenses.push({id:'exp-'+Date.now(),ts:now(),description,amount,by:session.id});note('Gasto administrativo: '+description+' '+money(amount));persist()};

function note(action){D.log.push({at:now(),action});if(D.log.length>300)D.log.shift()}
function nameOf(id){return D.staff.find(x=>x.id===id)?.name||'Sin identificar'}
function logged(){if(!session){alert('Inicia sesión en Personal y Turnos.');return false}return true}
function admin(){if(!session||session.role!=='admin'){alert('Esta operación corresponde a la administradora.');return false}return true}
function setSession(id,pin){const u=D.staff.find(x=>x.id===id&&x.pin===pin&&x.active!==false);if(!u){alert('Usuario o clave incorrectos.');return}session={id:u.id,role:u.role,name:u.name};turnosScreen='inicio';render()}
window.tnLogin=()=>setSession(field('tnUser'),field('tnPass'));
window.tnLogout=()=>{session=null;turnosScreen='inicio';render()};
window.tnSwitchReceiver=()=>{session=null;render();const e=document.getElementById('tnUser');const t=pending();if(e&&t){const u=D.staff.find(x=>x.role==='waitress'&&x.active!==false&&x.id!==t.staffId);if(u)e.value=u.id}document.getElementById('tnPass')?.focus()};
// Recuperación exclusiva del piloto local: conserva personal, turnos y datos comerciales.
// NO habilitar este mecanismo en una versión con autenticación real.
window.tnResetPilotAdmin=()=>{
  if(session)return alert('Cierra sesión del módulo antes de recuperar el acceso.');
  const admins=D.staff.filter(x=>x.role==='admin');
  if(admins.length!==1)return alert('No se puede recuperar automáticamente este registro.');
  const phrase=field('tnResetConfirm');
  const newPin=field('tnResetPass');
  if(phrase!=='REINICIAR')return alert('Escribe REINICIAR para confirmar el cambio de clave de prueba.');
  if(newPin.length<6)return alert('La nueva clave de prueba debe tener al menos 6 caracteres.');
  if(!confirm('¿Cambiar únicamente la clave de la administradora local? No se borrarán mesas, ventas, inventario, meseras ni turnos. Esta opción NO es segura para uso real.'))return;
  admins[0].pin=newPin;
  note('Recuperación de clave de administración del piloto local');
  persist();
  alert('Clave de prueba cambiada. Ya puedes iniciar sesión.');
};
window.tnTogglePassword=id=>{const el=document.getElementById(id);if(el)el.type=el.type==='password'?'text':'password'};
const passControl=(id,autocomplete='off')=>`<div class="tnPassword"><input id="${id}" type="password" autocomplete="${autocomplete}" autocapitalize="off" spellcheck="false"><button type="button" class="tnEye" onclick="tnTogglePassword('${id}')" aria-label="Mostrar u ocultar clave">👁️ Ver</button></div>`;

window.tnBootstrap=()=>{if(D.staff.length)return;let name=field('tnAdminName'),pin=field('tnAdminPass');if(name.length<2||pin.length<6)return alert('Indica nombre y una clave de al menos 6 caracteres.');D.staff.push({id:'admin-'+Date.now(),name,role:'admin',pin,active:true});note('Se creó la cuenta de administración local');persist();alert('Administradora registrada en este dispositivo. Inicia sesión para continuar.')};
window.tnCreateStaff=()=>{if(!admin())return;let name=field('tnStaffName'),pin=field('tnStaffPass');if(name.length<2||pin.length<6)return alert('Escribe nombre y clave de al menos 6 caracteres.');if(D.staff.some(x=>x.name.toLowerCase()===name.toLowerCase()))return alert('Ya existe ese nombre.');D.staff.push({id:'staff-'+Date.now(),name,role:'waitress',pin,active:true});note('Administración registró a '+name);persist()};
window.tnOpen=()=>{if(!logged())return;if(active()||pending())return alert('Hay un turno abierto o pendiente de entrega.');let base=number('tnBase'),kind=field('tnKind');if(!validMoney(base))return alert('Indica una base válida.');if(kind==='1'&&session.role!=='admin')return alert('La base del primer turno la registra la administradora.');if(kind==='2')return alert('El segundo turno debe iniciarse desde la recepción de caja del primero.');let who=field('tnAssigned');if(!who||!D.staff.some(x=>x.id===who&&x.role==='waitress'))return alert('Selecciona la mesera que recibe.');D.turns.push({id:'turn-'+Date.now(),kind:1,staffId:who,openedBy:session.id,start:now(),base,baseNotes:field('tnOpenNotes'),status:'open'});note('Apertura turno día · '+nameOf(who)+' · base '+money(base));persist()};
window.tnSaveWage=()=>{if(!logged())return;const t=active();if(!t)return alert('No hay turno abierto.');if(session.id!==t.staffId&&session.role!=='admin')return alert('Solo la mesera responsable o administración puede registrar el pago.');const wage=number('tnWage');if(!validMoney(wage))return alert('Registra un pago válido.');if(wage>t.base+salesBetween(t.start,now()).cash)return alert('El pago excede el efectivo disponible.');t.wage=wage;note('Pago de turno registrado: '+money(wage));persist()};
window.tnClose=()=>{if(!logged())return;let t=active();if(!t)return alert('No hay turno abierto.');if(session.id!==t.staffId&&session.role!=='admin')return alert('Solo la mesera responsable o administración puede cerrar.');let counted=number('tnCounted'),obs=field('tnOutgoingNotes');if(!validMoney(counted))return alert('Indica cuánto dinero se contó.');let end=now(),calc=expectedCash(t,end),sales=calc.sales,expected=calc.expected;if(expected<0)return alert('El pago de turno excede el efectivo disponible. Verifica los valores.');
if(Math.abs(counted-expected)>0.01&&!obs)return alert('Hay una diferencia. Es obligatorio registrar observaciones.');
t.closedAt=end;t.sales=sales;t.salesDetail=salesSummary(t,end);t.expected=expected;t.outgoingCount=counted;t.outgoingNotes=obs;t.closedBy=session.id;t.status='pending';t.reportSnapshot=reportHTML(t,end);t.inventorySnapshot=JSON.parse(JSON.stringify(((typeof S!=='undefined')?S:null)?.inventory||{}));note('Cierre declarado · '+nameOf(t.staffId)+' · '+money(counted));persist()};
window.tnReceive=()=>{if(!logged())return;let t=pending();if(!t||t.kind!==1)return alert('No hay entrega del primer turno pendiente.');if(session.role!=='waitress')return alert('Debe ingresar la mesera que recibe.');if(session.id===t.staffId)return alert('La misma mesera no puede entregar y recibir.');let counted=number('tnReceived'),obs=field('tnIncomingNotes');if(!validMoney(counted))return alert('Registra el dinero recibido.');if((counted!==t.expected||counted!==t.outgoingCount)&&!obs)return alert('Si lo recibido difiere de lo esperado o de lo declarado por quien entrega, registra observaciones.');t.receivedCount=counted;t.receivedBy=session.id;t.receivedAt=now();t.incomingNotes=obs;t.status='completed';D.turns.push({id:'turn-'+Date.now(),kind:2,staffId:session.id,openedBy:session.id,start:now(),base:counted,fromTurn:t.id,status:'open'});note('Entrega verificada · '+nameOf(session.id)+' · '+money(counted));persist()};
window.tnFinal=()=>{if(!admin())return;let t=pending();if(!t||t.kind!==2)return alert('No hay cierre nocturno pendiente.');if((D.verifiedClosures||[]).some(c=>c.date===dateKey(now())))return alert('Ya existe un cierre general verificado para hoy.');let counted=number('tnAdminCount'),obs=field('tnAdminNotes');if(!validMoney(counted))return alert('Indica el efectivo que recoge administración.');if(counted!==t.expected&&!obs)return alert('Registra observaciones por la diferencia.');t.receivedCount=counted;t.receivedBy=session.id;t.receivedAt=now();t.incomingNotes=obs;t.withdrawal=counted;t.status='completed';D.verifiedClosures||=[];D.verifiedClosures.push(closeSnapshot());note('Cierre general · retiro administración '+money(counted)+' · saldo operativo $0');persist()};
window.tnAdminSub=(which)=>{if(!admin())return;const el=document.getElementById('tnAdminSubPanel');if(!el)return;
 if(which==='pending'){const p=pending();el.innerHTML=`<h4>🔎 Cierre del día por verificar</h4>${(D.verifiedClosures||[]).some(c=>c.date===dateKey(now()))?'<p>El cierre de hoy ya está verificado y bloqueado.</p>':dailyHTML()}${p&&p.kind===2?'<p>El cierre nocturno pendiente se confirma en la pantalla Entrega de caja, después de revisar los importes.</p><button onclick="tnNavigate(\'entrega\')">Ir a verificar cierre nocturno</button>':'<p class="tnMuted">No hay cierre nocturno pendiente de confirmación.</p>'}`;}
 else{const a=[...(D.verifiedClosures||[])].reverse();el.innerHTML=`<h4>📚 Cierres verificados por día</h4>${a.map(c=>`<div class="tnLog"><b>${esc(c.date)}</b> · ${money(c.sales)} ventas · efectivo esperado ${money(c.expected)}<br><button onclick="tnShowVerified('${esc(c.id)}')">👁️ Ver reporte</button> <button onclick="tnPrintReport('${esc(c.id)}')">🖨️ Imprimir</button></div>`).join('')||'<p>No hay cierres generales verificados.</p>'}<div id="tnVerifiedDetail"></div>`;}
};
function render(){let root=document.getElementById('turnosPanel');if(!root)return;let t=active(),p=pending(),options=D.staff.filter(x=>x.role==='waitress'&&x.active!==false).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');let latest=D.turns.slice(-12).reverse();
let h='<div class="tnCard"><span class="tnPill">Piloto local · v4.19.47</span><p class="tnMuted">Este módulo guarda datos únicamente en este navegador. Todavía NO bloquea Billar/Consumo ni sincroniza usuarios entre dispositivos. Las claves locales no son seguras para uso real: utiliza claves de prueba, no contraseñas personales.</p></div>';
if(!D.staff.length){h+=`<div class="tnCard"><h3>🔐 Registrar administradora (primera vez)</h3><label>Nombre</label><input id="tnAdminName" autocomplete="off"><label>Clave de prueba (mínimo 6 caracteres)</label>${passControl("tnAdminPass")}<p class="tnMuted">Escribe una clave de prueba que recuerdes. Si el iPhone propone una clave automática, puedes reemplazarla y usar 👁️ Ver para comprobarla.</p><button class="gold" onclick="tnBootstrap()">Crear administración local</button></div>`}
else if(!session){h+=`<div class="tnCard"><h3>🔐 ${p&&p.kind===1?'Ingresar para recibir caja':'Ingresar a Personal y Turnos'}</h3>${p&&p.kind===1?'<p class="tnMuted">La entrega del turno de día está pendiente. Ingresa con el usuario y clave de la mesera entrante (no con la cuenta de quien entrega).</p>':''}<label>Usuario</label><select id="tnUser">${D.staff.filter(x=>x.active!==false).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} (${x.role==='admin'?'Administración':'Mesera'})</option>`).join('')}</select><label>Clave</label>${passControl("tnPass")}<button class="gold" onclick="tnLogin()">Ingresar</button><details class="tnRecovery"><summary>🔑 ¿Olvidaste la clave de prueba?</summary><p class="tnMuted">Solo para esta versión piloto. Permite cambiar la clave local sin borrar ventas, inventario, personal ni historial de turnos. No usar como seguridad definitiva.</p><label>Escribe REINICIAR para confirmar</label><input id="tnResetConfirm" autocomplete="off" placeholder="REINICIAR"><label>Nueva clave de prueba (mínimo 6 caracteres)</label>${passControl("tnResetPass")}<button type="button" onclick="tnResetPilotAdmin()">Restablecer clave de prueba</button></details></div>`}
else{
h+=`<div class="tnCard tnInline"><b>👤 ${esc(session.name)}</b><span class="tnPill">${session.role==='admin'?'Administradora':'Mesera'}</span><button onclick="tnLogout()">Cerrar sesión del módulo</button></div>`;
if(session.role==='admin')h+=`<div class="tnGrid"><div class="tnCard"><h3>👥 Registrar mesera</h3><label>Nombre de la mesera</label><input id="tnStaffName" autocomplete="off"><label>Clave de prueba</label>${passControl("tnStaffPass")}<button class="gold" onclick="tnCreateStaff()">Guardar mesera</button><p class="tnMuted">Registradas: ${D.staff.filter(x=>x.role==='waitress').map(x=>esc(x.name)).join(', ')||'Ninguna'}</p></div>${!t&&!p?`<div class="tnCard"><h3>🌤️ Abrir primer turno</h3><label>Mesera que recibe</label><select id="tnAssigned"><option value="">Seleccionar...</option>${options}</select><label>Base entregada (COP)</label><input id="tnBase" type="number" min="0" step="1" placeholder="150000"><input id="tnKind" type="hidden" value="1"><label>Observaciones iniciales (opcional)</label><textarea id="tnOpenNotes" placeholder="Ej. base en billetes y monedas..."></textarea><button class="gold" onclick="tnOpen()">Abrir turno de día</button></div>`:''}</div>`;
if(t){let calc=expectedCash(t,now()),ss=calc.sales,expected=calc.expected;h+=`<div class="tnCard"><h3>🟢 Turno ${t.kind===1?'día':'noche'} abierto</h3><p>Responsable: <b>${esc(nameOf(t.staffId))}</b></p><p>Base recibida: <b>${money(t.base)}</b></p><p>Ventas efectivo registradas: <b>${money(ss.cash)}</b></p><p>Transferencias registradas: <b>${money(ss.transfer)}</b> <small>(no son efectivo)</small></p><p><b>EFECTIVO ESPERADO (calculado automáticamente):</b> <span class="tnNumber">${money(expected)}</span></p>${reportHTML(t,now())}<p class="tnMuted">El esperado es provisional: base + cobros en efectivo − pago del turno. Otros gastos y retiros todavía requieren conciliación.</p>${session.id===t.staffId||session.role==='admin'?`<label>Pago de este turno en efectivo (COP)</label><input id="tnWage" type="number" min="0" step="1" value="${Number(t.wage)||0}"><button onclick="tnSaveWage()">Guardar pago del turno y actualizar esperado</button><label>Efectivo físico contado por quien entrega (no modifica el esperado)</label><input id="tnCounted" type="number" min="0" step="1"><label>Observaciones y anomalías del turno</label><textarea id="tnOutgoingNotes" placeholder="Faltantes, sobrantes, inventario, novedades... "></textarea><button class="gold" onclick="tnClose()">Cerrar turno y preparar entrega</button>`:''}</div>`}
if(p){if(p.kind===1&&session.role!=='waitress')h+=`<div class="tnCard"><h3>🔑 Siguiente paso: recibir caja</h3><p>La mesera entrante debe iniciar sesión con su propia clave para verificar el dinero entregado por <b>${esc(nameOf(p.staffId))}</b>.</p><button class="gold" onclick="tnSwitchReceiver()">👤 Cambiar a mesera que recibe</button><p class="tnMuted">No se borrarán los turnos ni los registros. Si aún no está registrada, créala arriba antes de cambiar de usuario.</p></div>`;h+=`<div class="tnCard"><h3>📋 Entrega pendiente · turno ${p.kind===1?'día':'noche'}</h3><p>Entrega: <b>${esc(nameOf(p.staffId))}</b></p><p>Esperado: <span class="tnNumber">${money(p.expected)}</span></p><p>Declarado por quien entrega: <b>${money(p.outgoingCount)}</b></p><p>Diferencia de salida frente al esperado: <b>${money(p.outgoingCount-p.expected)}</b> ${p.outgoingCount===p.expected?'✅ Exacto':p.outgoingCount>p.expected?'⬆️ Sobrante declarado':'⬇️ Faltante declarado'}</p><p>Observaciones de salida: ${esc(p.outgoingNotes||'Sin novedades registradas')}</p>${reportHTML(p,p.closedAt||now())}${p.kind===1&&session.role==='waitress'&&session.id!==p.staffId?`<label>Dinero físico contado por quien recibe (base real del siguiente turno)</label><p class="tnMuted">Compara tu conteo tanto con el efectivo esperado como con el valor declarado por la mesera saliente. Si hay diferencias, explica la novedad.</p><input id="tnReceived" type="number" min="0" step="1"><label>Observaciones de quien recibe</label><textarea id="tnIncomingNotes" placeholder="Verificación y anomalías..."></textarea><button class="gold" onclick="tnReceive()">Confirmar recepción y abrir noche</button>`:''}${p.kind===1&&session.role==='waitress'&&session.id===p.staffId?'<p class="tnMuted">Quien entrega no puede recibir su propia caja. Cierra sesión e ingresa con la mesera entrante.</p>':''}${p.kind===2&&session.role==='admin'?`<label>Efectivo recogido por administración</label><input id="tnAdminCount" type="number" min="0" step="1"><label>Observaciones de administración</label><textarea id="tnAdminNotes" placeholder="Verificación final..."></textarea><button class="gold" onclick="tnFinal()">Confirmar retiro total y cierre diario</button>`:''}</div>`}
if(session.role==='admin')h+=`<div class="tnCard tnAdminActions"><h3>🏛️ Administración y gastos</h3><div class="tnAdminActionGrid"><button class="gold" onclick="tnAdminSub('pending')">🔎 Cierres pendientes por verificar y cerrar</button><button onclick="tnAdminSub('verified')">📚 Consolidado de cierres por día</button></div><div id="tnAdminSubPanel"></div></div>`;
if(latest.length)h+=`<div class="tnCard"><h3>📚 Historial individual de cierres · solo lectura</h3>${latest.filter(x=>session.role==='admin'||x.staffId===session.id).map(x=>`<div class="tnLog"><b>${x.kind===1?'Día':'Noche'} · ${esc(nameOf(x.staffId))}</b> <span class="tnPill">${x.status==='open'?'Abierto':x.status==='pending'?'Pendiente':'Completado'}</span><p class="tnMuted">${new Date(x.start).toLocaleString('es-CO')} · base ${money(x.base)}</p>${x.expected!=null?`<p>Pago de turno: ${money(x.wage||0)} · esperado: ${money(x.expected)} · declarado: ${money(x.outgoingCount)} · recibido: ${x.receivedCount==null?'Pendiente':money(x.receivedCount)}</p><p>Diferencia recibido vs. esperado: <b>${x.receivedCount==null?'Pendiente':money(x.receivedCount-x.expected)}</b> · recibido vs. declarado: <b>${x.receivedCount==null?'Pendiente':money(x.receivedCount-x.outgoingCount)}</b></p><p>Observaciones: ${esc(x.outgoingNotes||'—')} / ${esc(x.incomingNotes||'—')}</p><button onclick="tnPrintReport('', '${esc(x.id)}')">🖨️ Imprimir reporte</button>`:''}</div>`).join('')}</div>`;
}
root.innerHTML=h;
if(session){
 const original=[...root.children];
 const panels={abrir:[],cerrar:[],entrega:[],administracion:[],historial:[]};
 const main=[];
 function category(el){const tx=el.textContent||'';
  if(el.classList.contains('tnGrid'))return 'abrir';
  if(tx.includes('Turno ')&&tx.includes(' abierto'))return 'cerrar';
  if(tx.includes('Entrega pendiente')||tx.includes('Siguiente paso: recibir caja'))return 'entrega';
  if(tx.includes('Consolidado')||tx.includes('Gastos de administración')||tx.includes('Cierre general'))return 'administracion';
  if(tx.includes('Historial de entregas'))return 'historial';
  return 'main';
 }
 for(const el of original){const key=category(el);if(key==='main')main.push(el);else panels[key].push(el)}
 root.replaceChildren();
 const shell=document.createElement('div');shell.className='tnWorkspace';
 const title=document.createElement('div');title.className='tnWorkspaceHeader';title.innerHTML='<div class="tnEyebrow">LA HERRADURA · CONTROL DE CAJA</div><h2>Personal y turnos</h2><p>Una tarea a la vez. Tus ventas y mesas siguen intactas.</p>';shell.append(title);main.forEach(x=>shell.append(x));
 const menu=document.createElement('div');menu.className='tnNavigation';
 const actions=[['inicio','⌂','Panel principal','Estado y accesos'],['abrir','▶','Iniciar turno','Base y observaciones'],['cerrar','▣','Cerrar turno','Ventas y arqueo'],['entrega','⇄','Entrega de caja','Recepción y verificación'],['administracion','▤','Administración','Consolidado y gastos'],['historial','◷','Historial','Turnos anteriores']];
 for(const [id,icon,label,sub] of actions){if(id==='administracion'&&session.role!=='admin')continue;const b=document.createElement('button');b.type='button';b.className='tnNavTile'+(turnosScreen===id?' isActive':'');b.innerHTML='<span class="tnNavIcon">'+icon+'</span><span><b>'+label+'</b><small>'+sub+'</small></span>';b.onclick=()=>window.tnNavigate(id);menu.append(b)}
 if(turnosScreen==='inicio'){
  const activeTurn=active(),pendingTurn=pending();const status=document.createElement('div');status.className='tnDashboardStatus';status.innerHTML='<span class="tnPill">'+(activeTurn?'● Turno activo':pendingTurn?'◉ Entrega pendiente':'○ Sin turno activo')+'</span><h3>'+(activeTurn?'Turno de '+(activeTurn.kind===1?'día':'noche'):pendingTurn?'Pendiente de recepción':'Listo para comenzar')+'</h3><p>'+(activeTurn?'Responsable: '+esc(nameOf(activeTurn.staffId))+' · Base: '+money(activeTurn.base):pendingTurn?'Esperado: '+money(pendingTurn.expected):'Selecciona Iniciar turno para registrar la base inicial.')+'</p>';shell.append(status);shell.append(menu);
 }else{
  const back=document.createElement('button');back.type='button';back.className='tnBack';back.textContent='← Volver al panel de turnos';back.onclick=()=>window.tnNavigate('inicio');shell.append(back);
  const section=document.createElement('div');section.className='tnScreen';const headings={abrir:'▶ Iniciar turno',cerrar:'▣ Finalizar turno y cierre de caja',entrega:'⇄ Entrega y recepción de caja',administracion:'▤ Consolidado de administración',historial:'◷ Historial de turnos'};const heading=document.createElement('h3');heading.textContent=headings[turnosScreen];section.append(heading);
  const group=panels[turnosScreen]||[];if(!group.length){const empty=document.createElement('div');empty.className='tnEmpty';empty.textContent=turnosScreen==='abrir'?'La apertura estará disponible cuando no exista un turno abierto o pendiente.':turnosScreen==='cerrar'?'No hay un turno abierto para cerrar.':turnosScreen==='entrega'?'No hay una entrega de caja pendiente.':'Todavía no hay registros en esta sección.';section.append(empty)}else group.forEach(x=>section.append(x));shell.append(section);
 }
 root.append(shell);
}
}
const orig=window.renderShift;
window.renderShift=function(){if(typeof orig==='function'){try{orig()}catch(e){}}const legacy=document.getElementById('shiftInfo');if(legacy)legacy.style.display='none';render()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
